<?php

use Illuminate\Database\Feeds;

class CitiesFeed {

    public static function feed() {
        return [
            0 => ['id' => '1', 'name' => 'Medellín', 'department' => 'Antioquia'],
            1 => ['id' => '2', 'name' => 'Abejorral', 'department' => 'Antioquia'],
            2 => ['id' => '3', 'name' => 'Abriaqui', 'department' => 'Antioquia'],
            3 => ['id' => '4', 'name' => 'Alejandría', 'department' => 'Antioquia'],
            4 => ['id' => '5', 'name' => 'Amaga', 'department' => 'Antioquia'],
            5 => ['id' => '6', 'name' => 'Amalfi', 'department' => 'Antioquia'],
            6 => ['id' => '7', 'name' => 'Andes', 'department' => 'Antioquia'],
            7 => ['id' => '8', 'name' => 'Angelopolis', 'department' => 'Antioquia'],
            8 => ['id' => '9', 'name' => 'Angostura', 'department' => 'Antioquia'],
            9 => ['id' => '10', 'name' => 'Anorí', 'department' => 'Antioquia'],
            10 => ['id' => '11', 'name' => 'Santafe de antioquia', 'department' => 'Antioquia'],
            11 => ['id' => '12', 'name' => 'Anza', 'department' => 'Antioquia'],
            12 => ['id' => '13', 'name' => 'Apartado', 'department' => 'Antioquia'],
            13 => ['id' => '14', 'name' => 'Arboletes', 'department' => 'Antioquia'],
            14 => ['id' => '15', 'name' => 'Argelia', 'department' => 'Antioquia'],
            15 => ['id' => '16', 'name' => 'Armenia', 'department' => 'Antioquia'],
            16 => ['id' => '17', 'name' => 'Barbosa', 'department' => 'Antioquia'],
            17 => ['id' => '18', 'name' => 'Belmira', 'department' => 'Antioquia'],
            18 => ['id' => '19', 'name' => 'Bello', 'department' => 'Antioquia'],
            19 => ['id' => '20', 'name' => 'Betania', 'department' => 'Antioquia'],
            20 => ['id' => '21', 'name' => 'Betulia', 'department' => 'Antioquia'],
            21 => ['id' => '22', 'name' => 'Ciudad bolivar', 'department' => 'Antioquia'],
            22 => ['id' => '23', 'name' => 'Briceño', 'department' => 'Antioquia'],
            23 => ['id' => '24', 'name' => 'Buriticá', 'department' => 'Antioquia'],
            24 => ['id' => '25', 'name' => 'Caceres', 'department' => 'Antioquia'],
            25 => ['id' => '26', 'name' => 'Caicedo', 'department' => 'Antioquia'],
            26 => ['id' => '27', 'name' => 'Caldas', 'department' => 'Antioquia'],
            27 => ['id' => '28', 'name' => 'Campamento', 'department' => 'Antioquia'],
            28 => ['id' => '29', 'name' => 'Cañasgordas', 'department' => 'Antioquia'],
            29 => ['id' => '30', 'name' => 'Caracolí', 'department' => 'Antioquia'],
            30 => ['id' => '31', 'name' => 'Caramanta', 'department' => 'Antioquia'],
            31 => ['id' => '32', 'name' => 'Carepa', 'department' => 'Antioquia'],
            32 => ['id' => '33', 'name' => 'El carmen de viboral', 'department' => 'Antioquia'],
            33 => ['id' => '34', 'name' => 'Carolina', 'department' => 'Antioquia'],
            34 => ['id' => '35', 'name' => 'Caucasia', 'department' => 'Antioquia'],
            35 => ['id' => '36', 'name' => 'Chigorodó', 'department' => 'Antioquia'],
            36 => ['id' => '37', 'name' => 'Cisneros', 'department' => 'Antioquia'],
            37 => ['id' => '38', 'name' => 'Cocorna', 'department' => 'Antioquia'],
            38 => ['id' => '39', 'name' => 'Concepcion', 'department' => 'Antioquia'],
            39 => ['id' => '40', 'name' => 'Concordia', 'department' => 'Antioquia'],
            40 => ['id' => '41', 'name' => 'Copacabana', 'department' => 'Antioquia'],
            41 => ['id' => '42', 'name' => 'Dabeiba', 'department' => 'Antioquia'],
            42 => ['id' => '43', 'name' => 'Don matias', 'department' => 'Antioquia'],
            43 => ['id' => '44', 'name' => 'Ebejico', 'department' => 'Antioquia'],
            44 => ['id' => '45', 'name' => 'El bagre', 'department' => 'Antioquia'],
            45 => ['id' => '46', 'name' => 'Entrerrios', 'department' => 'Antioquia'],
            46 => ['id' => '47', 'name' => 'Envigado', 'department' => 'Antioquia'],
            47 => ['id' => '48', 'name' => 'Fredonia', 'department' => 'Antioquia'],
            48 => ['id' => '49', 'name' => 'Frontino', 'department' => 'Antioquia'],
            49 => ['id' => '50', 'name' => 'Giraldo', 'department' => 'Antioquia'],
            50 => ['id' => '51', 'name' => 'Girardota', 'department' => 'Antioquia'],
            51 => ['id' => '52', 'name' => 'Gomez plata', 'department' => 'Antioquia'],
            52 => ['id' => '53', 'name' => 'Granada', 'department' => 'Antioquia'],
            53 => ['id' => '54', 'name' => 'Guadalupe', 'department' => 'Antioquia'],
            54 => ['id' => '55', 'name' => 'Guarne', 'department' => 'Antioquia'],
            55 => ['id' => '56', 'name' => 'Guatape', 'department' => 'Antioquia'],
            56 => ['id' => '57', 'name' => 'Heliconia', 'department' => 'Antioquia'],
            57 => ['id' => '58', 'name' => 'Hispania', 'department' => 'Antioquia'],
            58 => ['id' => '59', 'name' => 'Itagui', 'department' => 'Antioquia'],
            59 => ['id' => '60', 'name' => 'Ituango', 'department' => 'Antioquia'],
            60 => ['id' => '61', 'name' => 'Jardin', 'department' => 'Antioquia'],
            61 => ['id' => '62', 'name' => 'Jerico', 'department' => 'Antioquia'],
            62 => ['id' => '63', 'name' => 'La ceja', 'department' => 'Antioquia'],
            63 => ['id' => '64', 'name' => 'La estrella', 'department' => 'Antioquia'],
            64 => ['id' => '65', 'name' => 'La pintada', 'department' => 'Antioquia'],
            65 => ['id' => '66', 'name' => 'La unión', 'department' => 'Antioquia'],
            66 => ['id' => '67', 'name' => 'Liborina', 'department' => 'Antioquia'],
            67 => ['id' => '68', 'name' => 'Maceo', 'department' => 'Antioquia'],
            68 => ['id' => '69', 'name' => 'Marinilla', 'department' => 'Antioquia'],
            69 => ['id' => '70', 'name' => 'Montebello', 'department' => 'Antioquia'],
            70 => ['id' => '71', 'name' => 'Murindo', 'department' => 'Antioquia'],
            71 => ['id' => '72', 'name' => 'Mutata', 'department' => 'Antioquia'],
            72 => ['id' => '73', 'name' => 'Nariño', 'department' => 'Antioquia'],
            73 => ['id' => '74', 'name' => 'Necocli', 'department' => 'Antioquia'],
            74 => ['id' => '75', 'name' => 'Nechi', 'department' => 'Antioquia'],
            75 => ['id' => '76', 'name' => 'Olaya', 'department' => 'Antioquia'],
            76 => ['id' => '77', 'name' => 'Pe', 'department' => 'Antioquia'],
            77 => ['id' => '78', 'name' => 'Peque', 'department' => 'Antioquia'],
            78 => ['id' => '79', 'name' => 'Pueblorrico', 'department' => 'Antioquia'],
            79 => ['id' => '80', 'name' => 'Puerto berrio', 'department' => 'Antioquia'],
            80 => ['id' => '81', 'name' => 'Puerto nare', 'department' => 'Antioquia'],
            81 => ['id' => '82', 'name' => 'Puerto triunfo', 'department' => 'Antioquia'],
            82 => ['id' => '83', 'name' => 'Remedios', 'department' => 'Antioquia'],
            83 => ['id' => '84', 'name' => 'Retiro', 'department' => 'Antioquia'],
            84 => ['id' => '85', 'name' => 'Rionegro', 'department' => 'Antioquia'],
            85 => ['id' => '86', 'name' => 'Sabanalarga', 'department' => 'Antioquia'],
            86 => ['id' => '87', 'name' => 'Sabaneta', 'department' => 'Antioquia'],
            87 => ['id' => '88', 'name' => 'Salgar', 'department' => 'Antioquia'],
            88 => ['id' => '89', 'name' => 'San andres de cuerquia', 'department' => 'Antioquia'],
            89 => ['id' => '90', 'name' => 'San carlos', 'department' => 'Antioquia'],
            90 => ['id' => '91', 'name' => 'San francisco', 'department' => 'Antioquia'],
            91 => ['id' => '92', 'name' => 'San jeronimo', 'department' => 'Antioquia'],
            92 => ['id' => '93', 'name' => 'San jose de la montaña', 'department' => 'Antioquia'],
            93 => ['id' => '94', 'name' => 'San juan de uraba', 'department' => 'Antioquia'],
            94 => ['id' => '95', 'name' => 'San luis', 'department' => 'Antioquia'],
            95 => ['id' => '96', 'name' => 'San pedro', 'department' => 'Antioquia'],
            96 => ['id' => '97', 'name' => 'San pedro de uraba', 'department' => 'Antioquia'],
            97 => ['id' => '98', 'name' => 'San rafael', 'department' => 'Antioquia'],
            98 => ['id' => '99', 'name' => 'San roque', 'department' => 'Antioquia'],
            99 => ['id' => '100', 'name' => 'San vicente', 'department' => 'Antioquia'],
            100 => ['id' => '101', 'name' => 'Santa barbara', 'department' => 'Antioquia'],
            101 => ['id' => '102', 'name' => 'Santa rosa de osos', 'department' => 'Antioquia'],
            102 => ['id' => '103', 'name' => 'Santo domingo', 'department' => 'Antioquia'],
            103 => ['id' => '104', 'name' => 'El santuario', 'department' => 'Antioquia'],
            104 => ['id' => '105', 'name' => 'Segovia', 'department' => 'Antioquia'],
            105 => ['id' => '106', 'name' => 'Sonson', 'department' => 'Antioquia'],
            106 => ['id' => '107', 'name' => 'Sopetran', 'department' => 'Antioquia'],
            107 => ['id' => '108', 'name' => 'Tamesis', 'department' => 'Antioquia'],
            108 => ['id' => '109', 'name' => 'Taraza', 'department' => 'Antioquia'],
            109 => ['id' => '110', 'name' => 'Tarso', 'department' => 'Antioquia'],
            110 => ['id' => '111', 'name' => 'Titiribi', 'department' => 'Antioquia'],
            111 => ['id' => '112', 'name' => 'Toledo', 'department' => 'Antioquia'],
            112 => ['id' => '113', 'name' => 'Turbo', 'department' => 'Antioquia'],
            113 => ['id' => '114', 'name' => 'Uramita', 'department' => 'Antioquia'],
            114 => ['id' => '115', 'name' => 'Urrao', 'department' => 'Antioquia'],
            115 => ['id' => '116', 'name' => 'Valdivia', 'department' => 'Antioquia'],
            116 => ['id' => '117', 'name' => 'Valparaiso', 'department' => 'Antioquia'],
            117 => ['id' => '118', 'name' => 'Vegachi', 'department' => 'Antioquia'],
            118 => ['id' => '119', 'name' => 'Venecia', 'department' => 'Antioquia'],
            119 => ['id' => '120', 'name' => 'Vigia del fuerte', 'department' => 'Antioquia'],
            120 => ['id' => '121', 'name' => 'Yali', 'department' => 'Antioquia'],
            121 => ['id' => '122', 'name' => 'Yarumal', 'department' => 'Antioquia'],
            122 => ['id' => '123', 'name' => 'Yolombo', 'department' => 'Antioquia'],
            123 => ['id' => '124', 'name' => 'Yondo', 'department' => 'Antioquia'],
            124 => ['id' => '125', 'name' => 'Zaragoza', 'department' => 'Antioquia'],
            125 => ['id' => '126', 'name' => 'Barranquilla', 'department' => 'Atlantico'],
            126 => ['id' => '127', 'name' => 'Baranoa', 'department' => 'Atlantico'],
            127 => ['id' => '128', 'name' => 'Campo de la cruz', 'department' => 'Atlantico'],
            128 => ['id' => '129', 'name' => 'Candelaria', 'department' => 'Atlantico'],
            129 => ['id' => '130', 'name' => 'Galapa', 'department' => 'Atlantico'],
            130 => ['id' => '131', 'name' => 'Juan de acosta', 'department' => 'Atlantico'],
            131 => ['id' => '132', 'name' => 'Luruaco', 'department' => 'Atlantico'],
            132 => ['id' => '133', 'name' => 'Malambo', 'department' => 'Atlantico'],
            133 => ['id' => '134', 'name' => 'Manati', 'department' => 'Atlantico'],
            134 => ['id' => '135', 'name' => 'Palmar de varela', 'department' => 'Atlantico'],
            135 => ['id' => '136', 'name' => 'Piojo', 'department' => 'Atlantico'],
            136 => ['id' => '137', 'name' => 'Polonuevo', 'department' => 'Atlantico'],
            137 => ['id' => '138', 'name' => 'Ponedera', 'department' => 'Atlantico'],
            138 => ['id' => '139', 'name' => 'Puerto colombia', 'department' => 'Atlantico'],
            139 => ['id' => '140', 'name' => 'Repelon', 'department' => 'Atlantico'],
            140 => ['id' => '141', 'name' => 'Sabanagrande', 'department' => 'Atlantico'],
            141 => ['id' => '142', 'name' => 'Sabanalarga', 'department' => 'Atlantico'],
            142 => ['id' => '143', 'name' => 'Santa lucia', 'department' => 'Atlantico'],
            143 => ['id' => '144', 'name' => 'Santo tomas', 'department' => 'Atlantico'],
            144 => ['id' => '145', 'name' => 'Soledad', 'department' => 'Atlantico'],
            145 => ['id' => '146', 'name' => 'Suan', 'department' => 'Atlantico'],
            146 => ['id' => '147', 'name' => 'Tubara', 'department' => 'Atlantico'],
            147 => ['id' => '148', 'name' => 'Usiacuri', 'department' => 'Atlantico'],
            148 => ['id' => '149', 'name' => 'Bogota, d.c.', 'department' => 'Bogota'],
            149 => ['id' => '150', 'name' => 'Cartagena', 'department' => 'Bolivar'],
            150 => ['id' => '151', 'name' => 'Achi', 'department' => 'Bolivar'],
            151 => ['id' => '152', 'name' => 'Altos del rosario', 'department' => 'Bolivar'],
            152 => ['id' => '153', 'name' => 'Arenal', 'department' => 'Bolivar'],
            153 => ['id' => '154', 'name' => 'Arjona', 'department' => 'Bolivar'],
            154 => ['id' => '155', 'name' => 'Arroyohondo', 'department' => 'Bolivar'],
            155 => ['id' => '156', 'name' => 'Barranco de loba', 'department' => 'Bolivar'],
            156 => ['id' => '157', 'name' => 'Calamar', 'department' => 'Bolivar'],
            157 => ['id' => '158', 'name' => 'Cantagallo', 'department' => 'Bolivar'],
            158 => ['id' => '159', 'name' => 'Cicuco', 'department' => 'Bolivar'],
            159 => ['id' => '160', 'name' => 'Cordoba', 'department' => 'Bolivar'],
            160 => ['id' => '161', 'name' => 'Clemencia', 'department' => 'Bolivar'],
            161 => ['id' => '162', 'name' => 'El carmen de bolivar', 'department' => 'Bolivar'],
            162 => ['id' => '163', 'name' => 'El guamo', 'department' => 'Bolivar'],
            163 => ['id' => '164', 'name' => 'El peñon', 'department' => 'Bolivar'],
            164 => ['id' => '165', 'name' => 'Hatillo de loba', 'department' => 'Bolivar'],
            165 => ['id' => '166', 'name' => 'Magangue', 'department' => 'Bolivar'],
            166 => ['id' => '167', 'name' => 'Mahates', 'department' => 'Bolivar'],
            167 => ['id' => '168', 'name' => 'Margarita', 'department' => 'Bolivar'],
            168 => ['id' => '169', 'name' => 'Maria la baja', 'department' => 'Bolivar'],
            169 => ['id' => '170', 'name' => 'Montecristo', 'department' => 'Bolivar'],
            170 => ['id' => '171', 'name' => 'Mompos', 'department' => 'Bolivar'],
            171 => ['id' => '172', 'name' => 'Norosi', 'department' => 'Bolivar'],
            172 => ['id' => '173', 'name' => 'Morales', 'department' => 'Bolivar'],
            173 => ['id' => '174', 'name' => 'Pinillos', 'department' => 'Bolivar'],
            174 => ['id' => '175', 'name' => 'Regidor', 'department' => 'Bolivar'],
            175 => ['id' => '176', 'name' => 'Rio viejo', 'department' => 'Bolivar'],
            176 => ['id' => '177', 'name' => 'San cristobal', 'department' => 'Bolivar'],
            177 => ['id' => '178', 'name' => 'San estanislao', 'department' => 'Bolivar'],
            178 => ['id' => '179', 'name' => 'San fernando', 'department' => 'Bolivar'],
            179 => ['id' => '180', 'name' => 'San jacinto', 'department' => 'Bolivar'],
            180 => ['id' => '181', 'name' => 'San jacinto del cauca', 'department' => 'Bolivar'],
            181 => ['id' => '182', 'name' => 'San juan nepomuceno', 'department' => 'Bolivar'],
            182 => ['id' => '183', 'name' => 'San martin de loba', 'department' => 'Bolivar'],
            183 => ['id' => '184', 'name' => 'San pablo', 'department' => 'Bolivar'],
            184 => ['id' => '185', 'name' => 'Santa catalina', 'department' => 'Bolivar'],
            185 => ['id' => '186', 'name' => 'Santa rosa', 'department' => 'Bolivar'],
            186 => ['id' => '187', 'name' => 'Santa rosa del sur', 'department' => 'Bolivar'],
            187 => ['id' => '188', 'name' => 'Simiti', 'department' => 'Bolivar'],
            188 => ['id' => '189', 'name' => 'Soplaviento', 'department' => 'Bolivar'],
            189 => ['id' => '190', 'name' => 'Talaigua nuevo', 'department' => 'Bolivar'],
            190 => ['id' => '191', 'name' => 'Tiquisio', 'department' => 'Bolivar'],
            191 => ['id' => '192', 'name' => 'Turbaco', 'department' => 'Bolivar'],
            192 => ['id' => '193', 'name' => 'Turbana', 'department' => 'Bolivar'],
            193 => ['id' => '194', 'name' => 'Villanueva', 'department' => 'Bolivar'],
            194 => ['id' => '195', 'name' => 'Zambrano', 'department' => 'Bolivar'],
            195 => ['id' => '196', 'name' => 'Tunja', 'department' => 'Boyaca'],
            196 => ['id' => '197', 'name' => 'Almeida', 'department' => 'Boyaca'],
            197 => ['id' => '198', 'name' => 'Aquitania', 'department' => 'Boyaca'],
            198 => ['id' => '199', 'name' => 'Arcabuco', 'department' => 'Boyaca'],
            199 => ['id' => '200', 'name' => 'Belen', 'department' => 'Boyaca'],
            200 => ['id' => '201', 'name' => 'Berbeo', 'department' => 'Boyaca'],
            201 => ['id' => '202', 'name' => 'Beteitiva', 'department' => 'Boyaca'],
            202 => ['id' => '203', 'name' => 'Boavita', 'department' => 'Boyaca'],
            203 => ['id' => '204', 'name' => 'Boyaca', 'department' => 'Boyaca'],
            204 => ['id' => '205', 'name' => 'Briceño', 'department' => 'Boyaca'],
            205 => ['id' => '206', 'name' => 'Buenavista', 'department' => 'Boyaca'],
            206 => ['id' => '207', 'name' => 'Busbanza', 'department' => 'Boyaca'],
            207 => ['id' => '208', 'name' => 'Caldas', 'department' => 'Boyaca'],
            208 => ['id' => '209', 'name' => 'Campohermoso', 'department' => 'Boyaca'],
            209 => ['id' => '210', 'name' => 'Cerinza', 'department' => 'Boyaca'],
            210 => ['id' => '211', 'name' => 'Chinavita', 'department' => 'Boyaca'],
            211 => ['id' => '212', 'name' => 'Chiquinquira', 'department' => 'Boyaca'],
            212 => ['id' => '213', 'name' => 'Chiscas', 'department' => 'Boyaca'],
            213 => ['id' => '214', 'name' => 'Chita', 'department' => 'Boyaca'],
            214 => ['id' => '215', 'name' => 'Chitaraque', 'department' => 'Boyaca'],
            215 => ['id' => '216', 'name' => 'Chivata', 'department' => 'Boyaca'],
            216 => ['id' => '217', 'name' => 'Cienega', 'department' => 'Boyaca'],
            217 => ['id' => '218', 'name' => 'Combita', 'department' => 'Boyaca'],
            218 => ['id' => '219', 'name' => 'Coper', 'department' => 'Boyaca'],
            219 => ['id' => '220', 'name' => 'Corrales', 'department' => 'Boyaca'],
            220 => ['id' => '221', 'name' => 'Covarachia', 'department' => 'Boyaca'],
            221 => ['id' => '222', 'name' => 'Cubara', 'department' => 'Boyaca'],
            222 => ['id' => '223', 'name' => 'Cucaita', 'department' => 'Boyaca'],
            223 => ['id' => '224', 'name' => 'Cuitiva', 'department' => 'Boyaca'],
            224 => ['id' => '225', 'name' => 'Chiquiza', 'department' => 'Boyaca'],
            225 => ['id' => '226', 'name' => 'Chivor', 'department' => 'Boyaca'],
            226 => ['id' => '227', 'name' => 'Duitama', 'department' => 'Boyaca'],
            227 => ['id' => '228', 'name' => 'El cocuy', 'department' => 'Boyaca'],
            228 => ['id' => '229', 'name' => 'El espino', 'department' => 'Boyaca'],
            229 => ['id' => '230', 'name' => 'Firavitoba', 'department' => 'Boyaca'],
            230 => ['id' => '231', 'name' => 'Floresta', 'department' => 'Boyaca'],
            231 => ['id' => '232', 'name' => 'Gachantiva', 'department' => 'Boyaca'],
            232 => ['id' => '233', 'name' => 'Gameza', 'department' => 'Boyaca'],
            233 => ['id' => '234', 'name' => 'Garagoa', 'department' => 'Boyaca'],
            234 => ['id' => '235', 'name' => 'Guacamayas', 'department' => 'Boyaca'],
            235 => ['id' => '236', 'name' => 'Guateque', 'department' => 'Boyaca'],
            236 => ['id' => '237', 'name' => 'Guayata', 'department' => 'Boyaca'],
            237 => ['id' => '238', 'name' => 'Gsican', 'department' => 'Boyaca'],
            238 => ['id' => '239', 'name' => 'Iza', 'department' => 'Boyaca'],
            239 => ['id' => '240', 'name' => 'Jenesano', 'department' => 'Boyaca'],
            240 => ['id' => '241', 'name' => 'Jerico', 'department' => 'Boyaca'],
            241 => ['id' => '242', 'name' => 'Labranzagrande', 'department' => 'Boyaca'],
            242 => ['id' => '243', 'name' => 'La capilla', 'department' => 'Boyaca'],
            243 => ['id' => '244', 'name' => 'La victoria', 'department' => 'Boyaca'],
            244 => ['id' => '245', 'name' => 'La uvita', 'department' => 'Boyaca'],
            245 => ['id' => '246', 'name' => 'Villa de leyva', 'department' => 'Boyaca'],
            246 => ['id' => '247', 'name' => 'Macanal', 'department' => 'Boyaca'],
            247 => ['id' => '248', 'name' => 'Maripi', 'department' => 'Boyaca'],
            248 => ['id' => '249', 'name' => 'Miraflores', 'department' => 'Boyaca'],
            249 => ['id' => '250', 'name' => 'Mongua', 'department' => 'Boyaca'],
            250 => ['id' => '251', 'name' => 'Mongui', 'department' => 'Boyaca'],
            251 => ['id' => '252', 'name' => 'Moniquira', 'department' => 'Boyaca'],
            252 => ['id' => '253', 'name' => 'Motavita', 'department' => 'Boyaca'],
            253 => ['id' => '254', 'name' => 'Muzo', 'department' => 'Boyaca'],
            254 => ['id' => '255', 'name' => 'Nobsa', 'department' => 'Boyaca'],
            255 => ['id' => '256', 'name' => 'Nuevo colon', 'department' => 'Boyaca'],
            256 => ['id' => '257', 'name' => 'Oicata', 'department' => 'Boyaca'],
            257 => ['id' => '258', 'name' => 'Otanche', 'department' => 'Boyaca'],
            258 => ['id' => '259', 'name' => 'Pachavita', 'department' => 'Boyaca'],
            259 => ['id' => '260', 'name' => 'Paez', 'department' => 'Boyaca'],
            260 => ['id' => '261', 'name' => 'Paipa', 'department' => 'Boyaca'],
            261 => ['id' => '262', 'name' => 'Pajarito', 'department' => 'Boyaca'],
            262 => ['id' => '263', 'name' => 'Panqueba', 'department' => 'Boyaca'],
            263 => ['id' => '264', 'name' => 'Pauna', 'department' => 'Boyaca'],
            264 => ['id' => '265', 'name' => 'Paya', 'department' => 'Boyaca'],
            265 => ['id' => '266', 'name' => 'Paz de rio', 'department' => 'Boyaca'],
            266 => ['id' => '267', 'name' => 'Pesca', 'department' => 'Boyaca'],
            267 => ['id' => '268', 'name' => 'Pisba', 'department' => 'Boyaca'],
            268 => ['id' => '269', 'name' => 'Puerto boyaca', 'department' => 'Boyaca'],
            269 => ['id' => '270', 'name' => 'Quipama', 'department' => 'Boyaca'],
            270 => ['id' => '271', 'name' => 'Ramiriqui', 'department' => 'Boyaca'],
            271 => ['id' => '272', 'name' => 'Raquira', 'department' => 'Boyaca'],
            272 => ['id' => '273', 'name' => 'Rondon', 'department' => 'Boyaca'],
            273 => ['id' => '274', 'name' => 'Saboya', 'department' => 'Boyaca'],
            274 => ['id' => '275', 'name' => 'Sachica', 'department' => 'Boyaca'],
            275 => ['id' => '276', 'name' => 'Samaca', 'department' => 'Boyaca'],
            276 => ['id' => '277', 'name' => 'San eduardo', 'department' => 'Boyaca'],
            277 => ['id' => '278', 'name' => 'San jose de pare', 'department' => 'Boyaca'],
            278 => ['id' => '279', 'name' => 'San luis de gaceno', 'department' => 'Boyaca'],
            279 => ['id' => '280', 'name' => 'San mateo', 'department' => 'Boyaca'],
            280 => ['id' => '281', 'name' => 'San miguel de sema', 'department' => 'Boyaca'],
            281 => ['id' => '282', 'name' => 'San pablo de borbur', 'department' => 'Boyaca'],
            282 => ['id' => '283', 'name' => 'Santana', 'department' => 'Boyaca'],
            283 => ['id' => '284', 'name' => 'Santa maria', 'department' => 'Boyaca'],
            284 => ['id' => '285', 'name' => 'Santa rosa de viterbo', 'department' => 'Boyaca'],
            285 => ['id' => '286', 'name' => 'Santa sofia', 'department' => 'Boyaca'],
            286 => ['id' => '287', 'name' => 'Sativanorte', 'department' => 'Boyaca'],
            287 => ['id' => '288', 'name' => 'Sativasur', 'department' => 'Boyaca'],
            288 => ['id' => '289', 'name' => 'Siachoque', 'department' => 'Boyaca'],
            289 => ['id' => '290', 'name' => 'Soata', 'department' => 'Boyaca'],
            290 => ['id' => '291', 'name' => 'Socota', 'department' => 'Boyaca'],
            291 => ['id' => '292', 'name' => 'Socha', 'department' => 'Boyaca'],
            292 => ['id' => '293', 'name' => 'Sogamoso', 'department' => 'Boyaca'],
            293 => ['id' => '294', 'name' => 'Somondoco', 'department' => 'Boyaca'],
            294 => ['id' => '295', 'name' => 'Sora', 'department' => 'Boyaca'],
            295 => ['id' => '296', 'name' => 'Sotaquira', 'department' => 'Boyaca'],
            296 => ['id' => '297', 'name' => 'Soraca', 'department' => 'Boyaca'],
            297 => ['id' => '298', 'name' => 'Susacon', 'department' => 'Boyaca'],
            298 => ['id' => '299', 'name' => 'Sutamarchan', 'department' => 'Boyaca'],
            299 => ['id' => '300', 'name' => 'Sutatenza', 'department' => 'Boyaca'],
            300 => ['id' => '301', 'name' => 'Tasco', 'department' => 'Boyaca'],
            301 => ['id' => '302', 'name' => 'Tenza', 'department' => 'Boyaca'],
            302 => ['id' => '303', 'name' => 'Tibana', 'department' => 'Boyaca'],
            303 => ['id' => '304', 'name' => 'Tibasosa', 'department' => 'Boyaca'],
            304 => ['id' => '305', 'name' => 'Tinjaca', 'department' => 'Boyaca'],
            305 => ['id' => '306', 'name' => 'Tipacoque', 'department' => 'Boyaca'],
            306 => ['id' => '307', 'name' => 'Toca', 'department' => 'Boyaca'],
            307 => ['id' => '308', 'name' => 'Togsi', 'department' => 'Boyaca'],
            308 => ['id' => '309', 'name' => 'Topaga', 'department' => 'Boyaca'],
            309 => ['id' => '310', 'name' => 'Tota', 'department' => 'Boyaca'],
            310 => ['id' => '311', 'name' => 'Tunungua', 'department' => 'Boyaca'],
            311 => ['id' => '312', 'name' => 'Turmeque', 'department' => 'Boyaca'],
            312 => ['id' => '313', 'name' => 'Tuta', 'department' => 'Boyaca'],
            313 => ['id' => '314', 'name' => 'Tutaza', 'department' => 'Boyaca'],
            314 => ['id' => '315', 'name' => 'Umbita', 'department' => 'Boyaca'],
            315 => ['id' => '316', 'name' => 'Ventaquemada', 'department' => 'Boyaca'],
            316 => ['id' => '317', 'name' => 'Viracacha', 'department' => 'Boyaca'],
            317 => ['id' => '318', 'name' => 'Zetaquira', 'department' => 'Boyaca'],
            318 => ['id' => '319', 'name' => 'Manizales', 'department' => 'Caldas'],
            319 => ['id' => '320', 'name' => 'Aguadas', 'department' => 'Caldas'],
            320 => ['id' => '321', 'name' => 'Anserma', 'department' => 'Caldas'],
            321 => ['id' => '322', 'name' => 'Aranzazu', 'department' => 'Caldas'],
            322 => ['id' => '323', 'name' => 'Belalcazar', 'department' => 'Caldas'],
            323 => ['id' => '324', 'name' => 'Chinchina', 'department' => 'Caldas'],
            324 => ['id' => '325', 'name' => 'Filadelfia', 'department' => 'Caldas'],
            325 => ['id' => '326', 'name' => 'La dorada', 'department' => 'Caldas'],
            326 => ['id' => '327', 'name' => 'La merced', 'department' => 'Caldas'],
            327 => ['id' => '328', 'name' => 'Manzanares', 'department' => 'Caldas'],
            328 => ['id' => '329', 'name' => 'Marmato', 'department' => 'Caldas'],
            329 => ['id' => '330', 'name' => 'Marquetalia', 'department' => 'Caldas'],
            330 => ['id' => '331', 'name' => 'Marulanda', 'department' => 'Caldas'],
            331 => ['id' => '332', 'name' => 'Neira', 'department' => 'Caldas'],
            332 => ['id' => '333', 'name' => 'Norcasia', 'department' => 'Caldas'],
            333 => ['id' => '334', 'name' => 'Pacora', 'department' => 'Caldas'],
            334 => ['id' => '335', 'name' => 'Palestina', 'department' => 'Caldas'],
            335 => ['id' => '336', 'name' => 'Pensilvania', 'department' => 'Caldas'],
            336 => ['id' => '337', 'name' => 'Riosucio', 'department' => 'Caldas'],
            337 => ['id' => '338', 'name' => 'Risaralda', 'department' => 'Caldas'],
            338 => ['id' => '339', 'name' => 'Salamina', 'department' => 'Caldas'],
            339 => ['id' => '340', 'name' => 'Samana', 'department' => 'Caldas'],
            340 => ['id' => '341', 'name' => 'San jose', 'department' => 'Caldas'],
            341 => ['id' => '342', 'name' => 'Supia', 'department' => 'Caldas'],
            342 => ['id' => '343', 'name' => 'Victoria', 'department' => 'Caldas'],
            343 => ['id' => '344', 'name' => 'Villamaria', 'department' => 'Caldas'],
            344 => ['id' => '345', 'name' => 'Viterbo', 'department' => 'Caldas'],
            345 => ['id' => '346', 'name' => 'Florencia', 'department' => 'Caqueta'],
            346 => ['id' => '347', 'name' => 'Albania', 'department' => 'Caqueta'],
            347 => ['id' => '348', 'name' => 'Belen de los andaquies', 'department' => 'Caqueta'],
            348 => ['id' => '349', 'name' => 'Cartagena del chaira', 'department' => 'Caqueta'],
            349 => ['id' => '350', 'name' => 'Curillo', 'department' => 'Caqueta'],
            350 => ['id' => '351', 'name' => 'El doncello', 'department' => 'Caqueta'],
            351 => ['id' => '352', 'name' => 'El paujil', 'department' => 'Caqueta'],
            352 => ['id' => '353', 'name' => 'La montañita', 'department' => 'Caqueta'],
            353 => ['id' => '354', 'name' => 'Milan', 'department' => 'Caqueta'],
            354 => ['id' => '355', 'name' => 'Morelia', 'department' => 'Caqueta'],
            355 => ['id' => '356', 'name' => 'Puerto rico', 'department' => 'Caqueta'],
            356 => ['id' => '357', 'name' => 'San jose del fragua', 'department' => 'Caqueta'],
            357 => ['id' => '358', 'name' => 'San vicente del caguan', 'department' => 'Caqueta'],
            358 => ['id' => '359', 'name' => 'Solano', 'department' => 'Caqueta'],
            359 => ['id' => '360', 'name' => 'Solita', 'department' => 'Caqueta'],
            360 => ['id' => '361', 'name' => 'Valparaiso', 'department' => 'Caqueta'],
            361 => ['id' => '362', 'name' => 'Popayan', 'department' => 'Cauca'],
            362 => ['id' => '363', 'name' => 'Almaguer', 'department' => 'Cauca'],
            363 => ['id' => '364', 'name' => 'Argelia', 'department' => 'Cauca'],
            364 => ['id' => '365', 'name' => 'Balboa', 'department' => 'Cauca'],
            365 => ['id' => '366', 'name' => 'Bolivar', 'department' => 'Cauca'],
            366 => ['id' => '367', 'name' => 'Buenos aires', 'department' => 'Cauca'],
            367 => ['id' => '368', 'name' => 'Cajibio', 'department' => 'Cauca'],
            368 => ['id' => '369', 'name' => 'Caldono', 'department' => 'Cauca'],
            369 => ['id' => '370', 'name' => 'Caloto', 'department' => 'Cauca'],
            370 => ['id' => '371', 'name' => 'Corinto', 'department' => 'Cauca'],
            371 => ['id' => '372', 'name' => 'El tambo', 'department' => 'Cauca'],
            372 => ['id' => '373', 'name' => 'Florencia', 'department' => 'Cauca'],
            373 => ['id' => '374', 'name' => 'Guachene', 'department' => 'Cauca'],
            374 => ['id' => '375', 'name' => 'Guapi', 'department' => 'Cauca'],
            375 => ['id' => '376', 'name' => 'Inza', 'department' => 'Cauca'],
            376 => ['id' => '377', 'name' => 'Jambalo', 'department' => 'Cauca'],
            377 => ['id' => '378', 'name' => 'La sierra', 'department' => 'Cauca'],
            378 => ['id' => '379', 'name' => 'La vega', 'department' => 'Cauca'],
            379 => ['id' => '380', 'name' => 'Lopez', 'department' => 'Cauca'],
            380 => ['id' => '381', 'name' => 'Mercaderes', 'department' => 'Cauca'],
            381 => ['id' => '382', 'name' => 'Miranda', 'department' => 'Cauca'],
            382 => ['id' => '383', 'name' => 'Morales', 'department' => 'Cauca'],
            383 => ['id' => '384', 'name' => 'Padilla', 'department' => 'Cauca'],
            384 => ['id' => '385', 'name' => 'Paez', 'department' => 'Cauca'],
            385 => ['id' => '386', 'name' => 'Patia', 'department' => 'Cauca'],
            386 => ['id' => '387', 'name' => 'Piamonte', 'department' => 'Cauca'],
            387 => ['id' => '388', 'name' => 'Piendamo', 'department' => 'Cauca'],
            388 => ['id' => '389', 'name' => 'Puerto tejada', 'department' => 'Cauca'],
            389 => ['id' => '390', 'name' => 'Purace', 'department' => 'Cauca'],
            390 => ['id' => '391', 'name' => 'Rosas', 'department' => 'Cauca'],
            391 => ['id' => '392', 'name' => 'San sebastian', 'department' => 'Cauca'],
            392 => ['id' => '393', 'name' => 'Santander de quilichao', 'department' => 'Cauca'],
            393 => ['id' => '394', 'name' => 'Santa rosa', 'department' => 'Cauca'],
            394 => ['id' => '395', 'name' => 'Silvia', 'department' => 'Cauca'],
            395 => ['id' => '396', 'name' => 'Sotara', 'department' => 'Cauca'],
            396 => ['id' => '397', 'name' => 'Suarez', 'department' => 'Cauca'],
            397 => ['id' => '398', 'name' => 'Sucre', 'department' => 'Cauca'],
            398 => ['id' => '399', 'name' => 'Timbio', 'department' => 'Cauca'],
            399 => ['id' => '400', 'name' => 'Timbiqui', 'department' => 'Cauca'],
            400 => ['id' => '401', 'name' => 'Toribio', 'department' => 'Cauca'],
            401 => ['id' => '402', 'name' => 'Totoro', 'department' => 'Cauca'],
            402 => ['id' => '403', 'name' => 'Villa rica', 'department' => 'Cauca'],
            403 => ['id' => '404', 'name' => 'Valledupar', 'department' => 'Cesar'],
            404 => ['id' => '405', 'name' => 'Aguachica', 'department' => 'Cesar'],
            405 => ['id' => '406', 'name' => 'Agustin codazzi', 'department' => 'Cesar'],
            406 => ['id' => '407', 'name' => 'Astrea', 'department' => 'Cesar'],
            407 => ['id' => '408', 'name' => 'Becerril', 'department' => 'Cesar'],
            408 => ['id' => '409', 'name' => 'Bosconia', 'department' => 'Cesar'],
            409 => ['id' => '410', 'name' => 'Chimichagua', 'department' => 'Cesar'],
            410 => ['id' => '411', 'name' => 'Chiriguana', 'department' => 'Cesar'],
            411 => ['id' => '412', 'name' => 'Curumani', 'department' => 'Cesar'],
            412 => ['id' => '413', 'name' => 'El copey', 'department' => 'Cesar'],
            413 => ['id' => '414', 'name' => 'El paso', 'department' => 'Cesar'],
            414 => ['id' => '415', 'name' => 'Gamarra', 'department' => 'Cesar'],
            415 => ['id' => '416', 'name' => 'Gonzalez', 'department' => 'Cesar'],
            416 => ['id' => '417', 'name' => 'La gloria', 'department' => 'Cesar'],
            417 => ['id' => '418', 'name' => 'La jagua de ibirico', 'department' => 'Cesar'],
            418 => ['id' => '419', 'name' => 'Manaure', 'department' => 'Cesar'],
            419 => ['id' => '420', 'name' => 'Pailitas', 'department' => 'Cesar'],
            420 => ['id' => '421', 'name' => 'Pelaya', 'department' => 'Cesar'],
            421 => ['id' => '422', 'name' => 'Pueblo bello', 'department' => 'Cesar'],
            422 => ['id' => '423', 'name' => 'Rio de oro', 'department' => 'Cesar'],
            423 => ['id' => '424', 'name' => 'La paz', 'department' => 'Cesar'],
            424 => ['id' => '425', 'name' => 'San alberto', 'department' => 'Cesar'],
            425 => ['id' => '426', 'name' => 'San diego', 'department' => 'Cesar'],
            426 => ['id' => '427', 'name' => 'San martin', 'department' => 'Cesar'],
            427 => ['id' => '428', 'name' => 'Tamalameque', 'department' => 'Cesar'],
            428 => ['id' => '429', 'name' => 'Monteria', 'department' => 'Cordoba'],
            429 => ['id' => '430', 'name' => 'Ayapel', 'department' => 'Cordoba'],
            430 => ['id' => '431', 'name' => 'Buenavista', 'department' => 'Cordoba'],
            431 => ['id' => '432', 'name' => 'Canalete', 'department' => 'Cordoba'],
            432 => ['id' => '433', 'name' => 'Cerete', 'department' => 'Cordoba'],
            433 => ['id' => '434', 'name' => 'Chima', 'department' => 'Cordoba'],
            434 => ['id' => '435', 'name' => 'Chinu', 'department' => 'Cordoba'],
            435 => ['id' => '436', 'name' => 'Cienaga de oro', 'department' => 'Cordoba'],
            436 => ['id' => '437', 'name' => 'Cotorra', 'department' => 'Cordoba'],
            437 => ['id' => '438', 'name' => 'La apartada', 'department' => 'Cordoba'],
            438 => ['id' => '439', 'name' => 'Lorica', 'department' => 'Cordoba'],
            439 => ['id' => '440', 'name' => 'Los cordobas', 'department' => 'Cordoba'],
            440 => ['id' => '441', 'name' => 'Momil', 'department' => 'Cordoba'],
            441 => ['id' => '442', 'name' => 'Montelibano', 'department' => 'Cordoba'],
            442 => ['id' => '443', 'name' => 'Moñitos', 'department' => 'Cordoba'],
            443 => ['id' => '444', 'name' => 'Planeta rica', 'department' => 'Cordoba'],
            444 => ['id' => '445', 'name' => 'Pueblo nuevo', 'department' => 'Cordoba'],
            445 => ['id' => '446', 'name' => 'Puerto escondido', 'department' => 'Cordoba'],
            446 => ['id' => '447', 'name' => 'Puerto libertador', 'department' => 'Cordoba'],
            447 => ['id' => '448', 'name' => 'Purisima', 'department' => 'Cordoba'],
            448 => ['id' => '449', 'name' => 'Sahagun', 'department' => 'Cordoba'],
            449 => ['id' => '450', 'name' => 'San andres sotavento', 'department' => 'Cordoba'],
            450 => ['id' => '451', 'name' => 'San antero', 'department' => 'Cordoba'],
            451 => ['id' => '452', 'name' => 'San bernardo del viento', 'department' => 'Cordoba'],
            452 => ['id' => '453', 'name' => 'San carlos', 'department' => 'Cordoba'],
            453 => ['id' => '454', 'name' => 'San pelayo', 'department' => 'Cordoba'],
            454 => ['id' => '455', 'name' => 'Tierralta', 'department' => 'Cordoba'],
            455 => ['id' => '456', 'name' => 'Valencia', 'department' => 'Cordoba'],
            456 => ['id' => '457', 'name' => 'Agua de dios', 'department' => 'Cundinamarca'],
            457 => ['id' => '458', 'name' => 'Alban', 'department' => 'Cundinamarca'],
            458 => ['id' => '459', 'name' => 'Anapoima', 'department' => 'Cundinamarca'],
            459 => ['id' => '460', 'name' => 'Anolaima', 'department' => 'Cundinamarca'],
            460 => ['id' => '461', 'name' => 'Arbelaez', 'department' => 'Cundinamarca'],
            461 => ['id' => '462', 'name' => 'Beltran', 'department' => 'Cundinamarca'],
            462 => ['id' => '463', 'name' => 'Bituima', 'department' => 'Cundinamarca'],
            463 => ['id' => '464', 'name' => 'Bojaca', 'department' => 'Cundinamarca'],
            464 => ['id' => '465', 'name' => 'Cabrera', 'department' => 'Cundinamarca'],
            465 => ['id' => '466', 'name' => 'Cachipay', 'department' => 'Cundinamarca'],
            466 => ['id' => '467', 'name' => 'Cajica', 'department' => 'Cundinamarca'],
            467 => ['id' => '468', 'name' => 'Caparrapi', 'department' => 'Cundinamarca'],
            468 => ['id' => '469', 'name' => 'Caqueza', 'department' => 'Cundinamarca'],
            469 => ['id' => '470', 'name' => 'Carmen de carupa', 'department' => 'Cundinamarca'],
            470 => ['id' => '471', 'name' => 'Chaguani', 'department' => 'Cundinamarca'],
            471 => ['id' => '472', 'name' => 'Chia', 'department' => 'Cundinamarca'],
            472 => ['id' => '473', 'name' => 'Chipaque', 'department' => 'Cundinamarca'],
            473 => ['id' => '474', 'name' => 'Choachi', 'department' => 'Cundinamarca'],
            474 => ['id' => '475', 'name' => 'Choconta', 'department' => 'Cundinamarca'],
            475 => ['id' => '476', 'name' => 'Cogua', 'department' => 'Cundinamarca'],
            476 => ['id' => '477', 'name' => 'Cota', 'department' => 'Cundinamarca'],
            477 => ['id' => '478', 'name' => 'Cucunuba', 'department' => 'Cundinamarca'],
            478 => ['id' => '479', 'name' => 'El colegio', 'department' => 'Cundinamarca'],
            479 => ['id' => '480', 'name' => 'El peñon', 'department' => 'Cundinamarca'],
            480 => ['id' => '481', 'name' => 'El rosal', 'department' => 'Cundinamarca'],
            481 => ['id' => '482', 'name' => 'Facatativa', 'department' => 'Cundinamarca'],
            482 => ['id' => '483', 'name' => 'Fomeque', 'department' => 'Cundinamarca'],
            483 => ['id' => '484', 'name' => 'Fosca', 'department' => 'Cundinamarca'],
            484 => ['id' => '485', 'name' => 'Funza', 'department' => 'Cundinamarca'],
            485 => ['id' => '486', 'name' => 'Fuquene', 'department' => 'Cundinamarca'],
            486 => ['id' => '487', 'name' => 'Fusagasuga', 'department' => 'Cundinamarca'],
            487 => ['id' => '488', 'name' => 'Gachala', 'department' => 'Cundinamarca'],
            488 => ['id' => '489', 'name' => 'Gachancipa', 'department' => 'Cundinamarca'],
            489 => ['id' => '490', 'name' => 'Gacheta', 'department' => 'Cundinamarca'],
            490 => ['id' => '491', 'name' => 'Gama', 'department' => 'Cundinamarca'],
            491 => ['id' => '492', 'name' => 'Girardot', 'department' => 'Cundinamarca'],
            492 => ['id' => '493', 'name' => 'Granada', 'department' => 'Cundinamarca'],
            493 => ['id' => '494', 'name' => 'Guacheta', 'department' => 'Cundinamarca'],
            494 => ['id' => '495', 'name' => 'Guaduas', 'department' => 'Cundinamarca'],
            495 => ['id' => '496', 'name' => 'Guasca', 'department' => 'Cundinamarca'],
            496 => ['id' => '497', 'name' => 'Guataqui', 'department' => 'Cundinamarca'],
            497 => ['id' => '498', 'name' => 'Guatavita', 'department' => 'Cundinamarca'],
            498 => ['id' => '499', 'name' => 'Guayabal de siquima', 'department' => 'Cundinamarca'],
            499 => ['id' => '500', 'name' => 'Guayabetal', 'department' => 'Cundinamarca'],
            500 => ['id' => '501', 'name' => 'Gutierrez', 'department' => 'Cundinamarca'],
            501 => ['id' => '502', 'name' => 'Jerusalen', 'department' => 'Cundinamarca'],
            502 => ['id' => '503', 'name' => 'Junin', 'department' => 'Cundinamarca'],
            503 => ['id' => '504', 'name' => 'La calera', 'department' => 'Cundinamarca'],
            504 => ['id' => '505', 'name' => 'La mesa', 'department' => 'Cundinamarca'],
            505 => ['id' => '506', 'name' => 'La palma', 'department' => 'Cundinamarca'],
            506 => ['id' => '507', 'name' => 'La peña', 'department' => 'Cundinamarca'],
            507 => ['id' => '508', 'name' => 'La vega', 'department' => 'Cundinamarca'],
            508 => ['id' => '509', 'name' => 'Lenguazaque', 'department' => 'Cundinamarca'],
            509 => ['id' => '510', 'name' => 'Macheta', 'department' => 'Cundinamarca'],
            510 => ['id' => '511', 'name' => 'Madrid', 'department' => 'Cundinamarca'],
            511 => ['id' => '512', 'name' => 'Manta', 'department' => 'Cundinamarca'],
            512 => ['id' => '513', 'name' => 'Medina', 'department' => 'Cundinamarca'],
            513 => ['id' => '514', 'name' => 'Mosquera', 'department' => 'Cundinamarca'],
            514 => ['id' => '515', 'name' => 'Nariño', 'department' => 'Cundinamarca'],
            515 => ['id' => '516', 'name' => 'Nemocon', 'department' => 'Cundinamarca'],
            516 => ['id' => '517', 'name' => 'Nilo', 'department' => 'Cundinamarca'],
            517 => ['id' => '518', 'name' => 'Nimaima', 'department' => 'Cundinamarca'],
            518 => ['id' => '519', 'name' => 'Nocaima', 'department' => 'Cundinamarca'],
            519 => ['id' => '520', 'name' => 'Venecia', 'department' => 'Cundinamarca'],
            520 => ['id' => '521', 'name' => 'Pacho', 'department' => 'Cundinamarca'],
            521 => ['id' => '522', 'name' => 'Paime', 'department' => 'Cundinamarca'],
            522 => ['id' => '523', 'name' => 'Pandi', 'department' => 'Cundinamarca'],
            523 => ['id' => '524', 'name' => 'Paratebueno', 'department' => 'Cundinamarca'],
            524 => ['id' => '525', 'name' => 'Pasca', 'department' => 'Cundinamarca'],
            525 => ['id' => '526', 'name' => 'Puerto salgar', 'department' => 'Cundinamarca'],
            526 => ['id' => '527', 'name' => 'Puli', 'department' => 'Cundinamarca'],
            527 => ['id' => '528', 'name' => 'Quebradanegra', 'department' => 'Cundinamarca'],
            528 => ['id' => '529', 'name' => 'Quetame', 'department' => 'Cundinamarca'],
            529 => ['id' => '530', 'name' => 'Quipile', 'department' => 'Cundinamarca'],
            530 => ['id' => '531', 'name' => 'Apulo', 'department' => 'Cundinamarca'],
            531 => ['id' => '532', 'name' => 'Ricaurte', 'department' => 'Cundinamarca'],
            532 => ['id' => '533', 'name' => 'San antonio del tequendama', 'department' => 'Cundinamarca'],
            533 => ['id' => '534', 'name' => 'San bernardo', 'department' => 'Cundinamarca'],
            534 => ['id' => '535', 'name' => 'San cayetano', 'department' => 'Cundinamarca'],
            535 => ['id' => '536', 'name' => 'San francisco', 'department' => 'Cundinamarca'],
            536 => ['id' => '537', 'name' => 'San juan de rio seco', 'department' => 'Cundinamarca'],
            537 => ['id' => '538', 'name' => 'Sasaima', 'department' => 'Cundinamarca'],
            538 => ['id' => '539', 'name' => 'Sesquile', 'department' => 'Cundinamarca'],
            539 => ['id' => '540', 'name' => 'Sibate', 'department' => 'Cundinamarca'],
            540 => ['id' => '541', 'name' => 'Silvania', 'department' => 'Cundinamarca'],
            541 => ['id' => '542', 'name' => 'Simijaca', 'department' => 'Cundinamarca'],
            542 => ['id' => '543', 'name' => 'Soacha', 'department' => 'Cundinamarca'],
            543 => ['id' => '544', 'name' => 'Sopo', 'department' => 'Cundinamarca'],
            544 => ['id' => '545', 'name' => 'Subachoque', 'department' => 'Cundinamarca'],
            545 => ['id' => '546', 'name' => 'Suesca', 'department' => 'Cundinamarca'],
            546 => ['id' => '547', 'name' => 'Supata', 'department' => 'Cundinamarca'],
            547 => ['id' => '548', 'name' => 'Susa', 'department' => 'Cundinamarca'],
            548 => ['id' => '549', 'name' => 'Sutatausa', 'department' => 'Cundinamarca'],
            549 => ['id' => '550', 'name' => 'Tabio', 'department' => 'Cundinamarca'],
            550 => ['id' => '551', 'name' => 'Tausa', 'department' => 'Cundinamarca'],
            551 => ['id' => '552', 'name' => 'Tena', 'department' => 'Cundinamarca'],
            552 => ['id' => '553', 'name' => 'Tenjo', 'department' => 'Cundinamarca'],
            553 => ['id' => '554', 'name' => 'Tibacuy', 'department' => 'Cundinamarca'],
            554 => ['id' => '555', 'name' => 'Tibirita', 'department' => 'Cundinamarca'],
            555 => ['id' => '556', 'name' => 'Tocaima', 'department' => 'Cundinamarca'],
            556 => ['id' => '557', 'name' => 'Tocancipa', 'department' => 'Cundinamarca'],
            557 => ['id' => '558', 'name' => 'Topaipi', 'department' => 'Cundinamarca'],
            558 => ['id' => '559', 'name' => 'Ubala', 'department' => 'Cundinamarca'],
            559 => ['id' => '560', 'name' => 'Ubaque', 'department' => 'Cundinamarca'],
            560 => ['id' => '561', 'name' => 'Villa de san diego de ubate', 'department' => 'Cundinamarca'],
            561 => ['id' => '562', 'name' => 'Une', 'department' => 'Cundinamarca'],
            562 => ['id' => '563', 'name' => 'Utica', 'department' => 'Cundinamarca'],
            563 => ['id' => '564', 'name' => 'Vergara', 'department' => 'Cundinamarca'],
            564 => ['id' => '565', 'name' => 'Viani', 'department' => 'Cundinamarca'],
            565 => ['id' => '566', 'name' => 'Villagomez', 'department' => 'Cundinamarca'],
            566 => ['id' => '567', 'name' => 'Villapinzon', 'department' => 'Cundinamarca'],
            567 => ['id' => '568', 'name' => 'Villeta', 'department' => 'Cundinamarca'],
            568 => ['id' => '569', 'name' => 'Viota', 'department' => 'Cundinamarca'],
            569 => ['id' => '570', 'name' => 'Yacopi', 'department' => 'Cundinamarca'],
            570 => ['id' => '571', 'name' => 'Zipacon', 'department' => 'Cundinamarca'],
            571 => ['id' => '572', 'name' => 'Zipaquira', 'department' => 'Cundinamarca'],
            572 => ['id' => '573', 'name' => 'Quibdo', 'department' => 'Choco'],
            573 => ['id' => '574', 'name' => 'Acandi', 'department' => 'Choco'],
            574 => ['id' => '575', 'name' => 'Alto baudo', 'department' => 'Choco'],
            575 => ['id' => '576', 'name' => 'Atrato', 'department' => 'Choco'],
            576 => ['id' => '577', 'name' => 'Bagado', 'department' => 'Choco'],
            577 => ['id' => '578', 'name' => 'Bahia solano', 'department' => 'Choco'],
            578 => ['id' => '579', 'name' => 'Bajo baudo', 'department' => 'Choco'],
            579 => ['id' => '580', 'name' => 'Bojaya', 'department' => 'Choco'],
            580 => ['id' => '581', 'name' => 'El canton del san pablo', 'department' => 'Choco'],
            581 => ['id' => '582', 'name' => 'Carmen del darien', 'department' => 'Choco'],
            582 => ['id' => '583', 'name' => 'Certegui', 'department' => 'Choco'],
            583 => ['id' => '584', 'name' => 'Condoto', 'department' => 'Choco'],
            584 => ['id' => '585', 'name' => 'El carmen de atrato', 'department' => 'Choco'],
            585 => ['id' => '586', 'name' => 'El litoral del san juan', 'department' => 'Choco'],
            586 => ['id' => '587', 'name' => 'Istmina', 'department' => 'Choco'],
            587 => ['id' => '588', 'name' => 'Jurado', 'department' => 'Choco'],
            588 => ['id' => '589', 'name' => 'Lloro', 'department' => 'Choco'],
            589 => ['id' => '590', 'name' => 'Medio atrato', 'department' => 'Choco'],
            590 => ['id' => '591', 'name' => 'Medio baudo', 'department' => 'Choco'],
            591 => ['id' => '592', 'name' => 'Medio san juan', 'department' => 'Choco'],
            592 => ['id' => '593', 'name' => 'Novita', 'department' => 'Choco'],
            593 => ['id' => '594', 'name' => 'Nuqui', 'department' => 'Choco'],
            594 => ['id' => '595', 'name' => 'Rio iro', 'department' => 'Choco'],
            595 => ['id' => '596', 'name' => 'Rio quito', 'department' => 'Choco'],
            596 => ['id' => '597', 'name' => 'Riosucio', 'department' => 'Choco'],
            597 => ['id' => '598', 'name' => 'San jose del palmar', 'department' => 'Choco'],
            598 => ['id' => '599', 'name' => 'Sipi', 'department' => 'Choco'],
            599 => ['id' => '600', 'name' => 'Tado', 'department' => 'Choco'],
            600 => ['id' => '601', 'name' => 'Unguia', 'department' => 'Choco'],
            601 => ['id' => '602', 'name' => 'Unión panamericana', 'department' => 'Choco'],
            602 => ['id' => '603', 'name' => 'Neiva', 'department' => 'Huila'],
            603 => ['id' => '604', 'name' => 'Acevedo', 'department' => 'Huila'],
            604 => ['id' => '605', 'name' => 'Agrado', 'department' => 'Huila'],
            605 => ['id' => '606', 'name' => 'Aipe', 'department' => 'Huila'],
            606 => ['id' => '607', 'name' => 'Algeciras', 'department' => 'Huila'],
            607 => ['id' => '608', 'name' => 'Altamira', 'department' => 'Huila'],
            608 => ['id' => '609', 'name' => 'Baraya', 'department' => 'Huila'],
            609 => ['id' => '610', 'name' => 'Campoalegre', 'department' => 'Huila'],
            610 => ['id' => '611', 'name' => 'Colombia', 'department' => 'Huila'],
            611 => ['id' => '612', 'name' => 'Elias', 'department' => 'Huila'],
            612 => ['id' => '613', 'name' => 'Garzon', 'department' => 'Huila'],
            613 => ['id' => '614', 'name' => 'Gigante', 'department' => 'Huila'],
            614 => ['id' => '615', 'name' => 'Guadalupe', 'department' => 'Huila'],
            615 => ['id' => '616', 'name' => 'Hobo', 'department' => 'Huila'],
            616 => ['id' => '617', 'name' => 'Iquira', 'department' => 'Huila'],
            617 => ['id' => '618', 'name' => 'Isnos', 'department' => 'Huila'],
            618 => ['id' => '619', 'name' => 'La argentina', 'department' => 'Huila'],
            619 => ['id' => '620', 'name' => 'La plata', 'department' => 'Huila'],
            620 => ['id' => '621', 'name' => 'Nataga', 'department' => 'Huila'],
            621 => ['id' => '622', 'name' => 'Oporapa', 'department' => 'Huila'],
            622 => ['id' => '623', 'name' => 'Paicol', 'department' => 'Huila'],
            623 => ['id' => '624', 'name' => 'Palermo', 'department' => 'Huila'],
            624 => ['id' => '625', 'name' => 'Palestina', 'department' => 'Huila'],
            625 => ['id' => '626', 'name' => 'Pital', 'department' => 'Huila'],
            626 => ['id' => '627', 'name' => 'Pitalito', 'department' => 'Huila'],
            627 => ['id' => '628', 'name' => 'Rivera', 'department' => 'Huila'],
            628 => ['id' => '629', 'name' => 'Saladoblanco', 'department' => 'Huila'],
            629 => ['id' => '630', 'name' => 'San agustin', 'department' => 'Huila'],
            630 => ['id' => '631', 'name' => 'Santa maria', 'department' => 'Huila'],
            631 => ['id' => '632', 'name' => 'Suaza', 'department' => 'Huila'],
            632 => ['id' => '633', 'name' => 'Tarqui', 'department' => 'Huila'],
            633 => ['id' => '634', 'name' => 'Tesalia', 'department' => 'Huila'],
            634 => ['id' => '635', 'name' => 'Tello', 'department' => 'Huila'],
            635 => ['id' => '636', 'name' => 'Teruel', 'department' => 'Huila'],
            636 => ['id' => '637', 'name' => 'Timana', 'department' => 'Huila'],
            637 => ['id' => '638', 'name' => 'Villavieja', 'department' => 'Huila'],
            638 => ['id' => '639', 'name' => 'Yaguara', 'department' => 'Huila'],
            639 => ['id' => '640', 'name' => 'Riohacha', 'department' => 'La guajira'],
            640 => ['id' => '641', 'name' => 'Albania', 'department' => 'La guajira'],
            641 => ['id' => '642', 'name' => 'Barrancas', 'department' => 'La guajira'],
            642 => ['id' => '643', 'name' => 'Dibulla', 'department' => 'La guajira'],
            643 => ['id' => '644', 'name' => 'Distraccion', 'department' => 'La guajira'],
            644 => ['id' => '645', 'name' => 'El molino', 'department' => 'La guajira'],
            645 => ['id' => '646', 'name' => 'Fonseca', 'department' => 'La guajira'],
            646 => ['id' => '647', 'name' => 'Hatonuevo', 'department' => 'La guajira'],
            647 => ['id' => '648', 'name' => 'La jagua del pilar', 'department' => 'La guajira'],
            648 => ['id' => '649', 'name' => 'Maicao', 'department' => 'La guajira'],
            649 => ['id' => '650', 'name' => 'Manaure', 'department' => 'La guajira'],
            650 => ['id' => '651', 'name' => 'San juan del cesar', 'department' => 'La guajira'],
            651 => ['id' => '652', 'name' => 'Uribia', 'department' => 'La guajira'],
            652 => ['id' => '653', 'name' => 'Urumita', 'department' => 'La guajira'],
            653 => ['id' => '654', 'name' => 'Villanueva', 'department' => 'La guajira'],
            654 => ['id' => '655', 'name' => 'Santa marta', 'department' => 'Magdalena'],
            655 => ['id' => '656', 'name' => 'Algarrobo', 'department' => 'Magdalena'],
            656 => ['id' => '657', 'name' => 'Aracataca', 'department' => 'Magdalena'],
            657 => ['id' => '658', 'name' => 'Ariguani', 'department' => 'Magdalena'],
            658 => ['id' => '659', 'name' => 'Cerro san antonio', 'department' => 'Magdalena'],
            659 => ['id' => '660', 'name' => 'Chibolo', 'department' => 'Magdalena'],
            660 => ['id' => '661', 'name' => 'Cienaga', 'department' => 'Magdalena'],
            661 => ['id' => '662', 'name' => 'Concordia', 'department' => 'Magdalena'],
            662 => ['id' => '663', 'name' => 'El banco', 'department' => 'Magdalena'],
            663 => ['id' => '664', 'name' => 'El piñon', 'department' => 'Magdalena'],
            664 => ['id' => '665', 'name' => 'El reten', 'department' => 'Magdalena'],
            665 => ['id' => '666', 'name' => 'Fundacion', 'department' => 'Magdalena'],
            666 => ['id' => '667', 'name' => 'Guamal', 'department' => 'Magdalena'],
            667 => ['id' => '668', 'name' => 'Nueva granada', 'department' => 'Magdalena'],
            668 => ['id' => '669', 'name' => 'Pedraza', 'department' => 'Magdalena'],
            669 => ['id' => '670', 'name' => 'Pijiño del carmen', 'department' => 'Magdalena'],
            670 => ['id' => '671', 'name' => 'Pivijay', 'department' => 'Magdalena'],
            671 => ['id' => '672', 'name' => 'Plato', 'department' => 'Magdalena'],
            672 => ['id' => '673', 'name' => 'Puebloviejo', 'department' => 'Magdalena'],
            673 => ['id' => '674', 'name' => 'Remolino', 'department' => 'Magdalena'],
            674 => ['id' => '675', 'name' => 'Sabanas de san angel', 'department' => 'Magdalena'],
            675 => ['id' => '676', 'name' => 'Salamina', 'department' => 'Magdalena'],
            676 => ['id' => '677', 'name' => 'San sebastian de buenavista', 'department' => 'Magdalena'],
            677 => ['id' => '678', 'name' => 'San zenon', 'department' => 'Magdalena'],
            678 => ['id' => '679', 'name' => 'Santa ana', 'department' => 'Magdalena'],
            679 => ['id' => '680', 'name' => 'Santa barbara de pinto', 'department' => 'Magdalena'],
            680 => ['id' => '681', 'name' => 'Sitionuevo', 'department' => 'Magdalena'],
            681 => ['id' => '682', 'name' => 'Tenerife', 'department' => 'Magdalena'],
            682 => ['id' => '683', 'name' => 'Zapayan', 'department' => 'Magdalena'],
            683 => ['id' => '684', 'name' => 'Zona bananera', 'department' => 'Magdalena'],
            684 => ['id' => '685', 'name' => 'Villavicencio', 'department' => 'Meta'],
            685 => ['id' => '686', 'name' => 'Acacias', 'department' => 'Meta'],
            686 => ['id' => '687', 'name' => 'Barranca de upia', 'department' => 'Meta'],
            687 => ['id' => '688', 'name' => 'Cabuyaro', 'department' => 'Meta'],
            688 => ['id' => '689', 'name' => 'Castilla la nueva', 'department' => 'Meta'],
            689 => ['id' => '690', 'name' => 'Cubarral', 'department' => 'Meta'],
            690 => ['id' => '691', 'name' => 'Cumaral', 'department' => 'Meta'],
            691 => ['id' => '692', 'name' => 'El calvario', 'department' => 'Meta'],
            692 => ['id' => '693', 'name' => 'El castillo', 'department' => 'Meta'],
            693 => ['id' => '694', 'name' => 'El dorado', 'department' => 'Meta'],
            694 => ['id' => '695', 'name' => 'Fuente de oro', 'department' => 'Meta'],
            695 => ['id' => '696', 'name' => 'Granada', 'department' => 'Meta'],
            696 => ['id' => '697', 'name' => 'Guamal', 'department' => 'Meta'],
            697 => ['id' => '698', 'name' => 'Mapiripan', 'department' => 'Meta'],
            698 => ['id' => '699', 'name' => 'Mesetas', 'department' => 'Meta'],
            699 => ['id' => '700', 'name' => 'La macarena', 'department' => 'Meta'],
            700 => ['id' => '701', 'name' => 'Uribe', 'department' => 'Meta'],
            701 => ['id' => '702', 'name' => 'Lejanias', 'department' => 'Meta'],
            702 => ['id' => '703', 'name' => 'Puerto concordia', 'department' => 'Meta'],
            703 => ['id' => '704', 'name' => 'Puerto gaitan', 'department' => 'Meta'],
            704 => ['id' => '705', 'name' => 'Puerto lopez', 'department' => 'Meta'],
            705 => ['id' => '706', 'name' => 'Puerto lleras', 'department' => 'Meta'],
            706 => ['id' => '707', 'name' => 'Puerto rico', 'department' => 'Meta'],
            707 => ['id' => '708', 'name' => 'Restrepo', 'department' => 'Meta'],
            708 => ['id' => '709', 'name' => 'San carlos de guaroa', 'department' => 'Meta'],
            709 => ['id' => '710', 'name' => 'San juan de arama', 'department' => 'Meta'],
            710 => ['id' => '711', 'name' => 'San juanito', 'department' => 'Meta'],
            711 => ['id' => '712', 'name' => 'San martin', 'department' => 'Meta'],
            712 => ['id' => '713', 'name' => 'Vistahermosa', 'department' => 'Meta'],
            713 => ['id' => '714', 'name' => 'Pasto', 'department' => 'Nariño'],
            714 => ['id' => '715', 'name' => 'Alban', 'department' => 'Nariño'],
            715 => ['id' => '716', 'name' => 'Aldana', 'department' => 'Nariño'],
            716 => ['id' => '717', 'name' => 'Ancuya', 'department' => 'Nariño'],
            717 => ['id' => '718', 'name' => 'Arboleda', 'department' => 'Nariño'],
            718 => ['id' => '719', 'name' => 'Barbacoas', 'department' => 'Nariño'],
            719 => ['id' => '720', 'name' => 'Belen', 'department' => 'Nariño'],
            720 => ['id' => '721', 'name' => 'Buesaco', 'department' => 'Nariño'],
            721 => ['id' => '722', 'name' => 'Colon', 'department' => 'Nariño'],
            722 => ['id' => '723', 'name' => 'Consaca', 'department' => 'Nariño'],
            723 => ['id' => '724', 'name' => 'Contadero', 'department' => 'Nariño'],
            724 => ['id' => '725', 'name' => 'Cordoba', 'department' => 'Nariño'],
            725 => ['id' => '726', 'name' => 'Cuaspud', 'department' => 'Nariño'],
            726 => ['id' => '727', 'name' => 'Cumbal', 'department' => 'Nariño'],
            727 => ['id' => '728', 'name' => 'Cumbitara', 'department' => 'Nariño'],
            728 => ['id' => '729', 'name' => 'Chachagsi', 'department' => 'Nariño'],
            729 => ['id' => '730', 'name' => 'El charco', 'department' => 'Nariño'],
            730 => ['id' => '731', 'name' => 'El peñol', 'department' => 'Nariño'],
            731 => ['id' => '732', 'name' => 'El rosario', 'department' => 'Nariño'],
            732 => ['id' => '733', 'name' => 'El tablon de gomez', 'department' => 'Nariño'],
            733 => ['id' => '734', 'name' => 'El tambo', 'department' => 'Nariño'],
            734 => ['id' => '735', 'name' => 'Funes', 'department' => 'Nariño'],
            735 => ['id' => '736', 'name' => 'Guachucal', 'department' => 'Nariño'],
            736 => ['id' => '737', 'name' => 'Guaitarilla', 'department' => 'Nariño'],
            737 => ['id' => '738', 'name' => 'Gualmatan', 'department' => 'Nariño'],
            738 => ['id' => '739', 'name' => 'Iles', 'department' => 'Nariño'],
            739 => ['id' => '740', 'name' => 'Imues', 'department' => 'Nariño'],
            740 => ['id' => '741', 'name' => 'Ipiales', 'department' => 'Nariño'],
            741 => ['id' => '742', 'name' => 'La cruz', 'department' => 'Nariño'],
            742 => ['id' => '743', 'name' => 'La florida', 'department' => 'Nariño'],
            743 => ['id' => '744', 'name' => 'La llanada', 'department' => 'Nariño'],
            744 => ['id' => '745', 'name' => 'La tola', 'department' => 'Nariño'],
            745 => ['id' => '746', 'name' => 'La unión', 'department' => 'Nariño'],
            746 => ['id' => '747', 'name' => 'Leiva', 'department' => 'Nariño'],
            747 => ['id' => '748', 'name' => 'Linares', 'department' => 'Nariño'],
            748 => ['id' => '749', 'name' => 'Los andes', 'department' => 'Nariño'],
            749 => ['id' => '750', 'name' => 'Magsi', 'department' => 'Nariño'],
            750 => ['id' => '751', 'name' => 'Mallama', 'department' => 'Nariño'],
            751 => ['id' => '752', 'name' => 'Mosquera', 'department' => 'Nariño'],
            752 => ['id' => '753', 'name' => 'Nariño', 'department' => 'Nariño'],
            753 => ['id' => '754', 'name' => 'Olaya herrera', 'department' => 'Nariño'],
            754 => ['id' => '755', 'name' => 'Ospina', 'department' => 'Nariño'],
            755 => ['id' => '756', 'name' => 'Francisco pizarro', 'department' => 'Nariño'],
            756 => ['id' => '757', 'name' => 'Policarpa', 'department' => 'Nariño'],
            757 => ['id' => '758', 'name' => 'Potosi', 'department' => 'Nariño'],
            758 => ['id' => '759', 'name' => 'Providencia', 'department' => 'Nariño'],
            759 => ['id' => '760', 'name' => 'Puerres', 'department' => 'Nariño'],
            760 => ['id' => '761', 'name' => 'Pupiales', 'department' => 'Nariño'],
            761 => ['id' => '762', 'name' => 'Ricaurte', 'department' => 'Nariño'],
            762 => ['id' => '763', 'name' => 'Roberto payan', 'department' => 'Nariño'],
            763 => ['id' => '764', 'name' => 'Samaniego', 'department' => 'Nariño'],
            764 => ['id' => '765', 'name' => 'Sandona', 'department' => 'Nariño'],
            765 => ['id' => '766', 'name' => 'San bernardo', 'department' => 'Nariño'],
            766 => ['id' => '767', 'name' => 'San lorenzo', 'department' => 'Nariño'],
            767 => ['id' => '768', 'name' => 'San pablo', 'department' => 'Nariño'],
            768 => ['id' => '769', 'name' => 'San pedro de cartago', 'department' => 'Nariño'],
            769 => ['id' => '770', 'name' => 'Santa barbara', 'department' => 'Nariño'],
            770 => ['id' => '771', 'name' => 'Santacruz', 'department' => 'Nariño'],
            771 => ['id' => '772', 'name' => 'Sapuyes', 'department' => 'Nariño'],
            772 => ['id' => '773', 'name' => 'Taminango', 'department' => 'Nariño'],
            773 => ['id' => '774', 'name' => 'Tangua', 'department' => 'Nariño'],
            774 => ['id' => '775', 'name' => 'San andres de tumaco', 'department' => 'Nariño'],
            775 => ['id' => '776', 'name' => 'Tuquerres', 'department' => 'Nariño'],
            776 => ['id' => '777', 'name' => 'Yacuanquer', 'department' => 'Nariño'],
            777 => ['id' => '778', 'name' => 'Cucuta', 'department' => 'N. de santander'],
            778 => ['id' => '779', 'name' => 'Abrego', 'department' => 'N. de santander'],
            779 => ['id' => '780', 'name' => 'Arboledas', 'department' => 'N. de santander'],
            780 => ['id' => '781', 'name' => 'Bochalema', 'department' => 'N. de santander'],
            781 => ['id' => '782', 'name' => 'Bucarasica', 'department' => 'N. de santander'],
            782 => ['id' => '783', 'name' => 'Cacota', 'department' => 'N. de santander'],
            783 => ['id' => '784', 'name' => 'Cachira', 'department' => 'N. de santander'],
            784 => ['id' => '785', 'name' => 'Chinacota', 'department' => 'N. de santander'],
            785 => ['id' => '786', 'name' => 'Chitaga', 'department' => 'N. de santander'],
            786 => ['id' => '787', 'name' => 'Convencion', 'department' => 'N. de santander'],
            787 => ['id' => '788', 'name' => 'Cucutilla', 'department' => 'N. de santander'],
            788 => ['id' => '789', 'name' => 'Durania', 'department' => 'N. de santander'],
            789 => ['id' => '790', 'name' => 'El carmen', 'department' => 'N. de santander'],
            790 => ['id' => '791', 'name' => 'El tarra', 'department' => 'N. de santander'],
            791 => ['id' => '792', 'name' => 'El zulia', 'department' => 'N. de santander'],
            792 => ['id' => '793', 'name' => 'Gramalote', 'department' => 'N. de santander'],
            793 => ['id' => '794', 'name' => 'Hacari', 'department' => 'N. de santander'],
            794 => ['id' => '795', 'name' => 'Herran', 'department' => 'N. de santander'],
            795 => ['id' => '796', 'name' => 'Labateca', 'department' => 'N. de santander'],
            796 => ['id' => '797', 'name' => 'La esperanza', 'department' => 'N. de santander'],
            797 => ['id' => '798', 'name' => 'La playa', 'department' => 'N. de santander'],
            798 => ['id' => '799', 'name' => 'Los patios', 'department' => 'N. de santander'],
            799 => ['id' => '800', 'name' => 'Lourdes', 'department' => 'N. de santander'],
            800 => ['id' => '801', 'name' => 'Mutiscua', 'department' => 'N. de santander'],
            801 => ['id' => '802', 'name' => 'Ocaña', 'department' => 'N. de santander'],
            802 => ['id' => '803', 'name' => 'Pamplona', 'department' => 'N. de santander'],
            803 => ['id' => '804', 'name' => 'Pamplonita', 'department' => 'N. de santander'],
            804 => ['id' => '805', 'name' => 'Puerto santander', 'department' => 'N. de santander'],
            805 => ['id' => '806', 'name' => 'Ragonvalia', 'department' => 'N. de santander'],
            806 => ['id' => '807', 'name' => 'Salazar', 'department' => 'N. de santander'],
            807 => ['id' => '808', 'name' => 'San calixto', 'department' => 'N. de santander'],
            808 => ['id' => '809', 'name' => 'San cayetano', 'department' => 'N. de santander'],
            809 => ['id' => '810', 'name' => 'Santiago', 'department' => 'N. de santander'],
            810 => ['id' => '811', 'name' => 'Sardinata', 'department' => 'N. de santander'],
            811 => ['id' => '812', 'name' => 'Silos', 'department' => 'N. de santander'],
            812 => ['id' => '813', 'name' => 'Teorama', 'department' => 'N. de santander'],
            813 => ['id' => '814', 'name' => 'Tibu', 'department' => 'N. de santander'],
            814 => ['id' => '815', 'name' => 'Toledo', 'department' => 'N. de santander'],
            815 => ['id' => '816', 'name' => 'Villa caro', 'department' => 'N. de santander'],
            816 => ['id' => '817', 'name' => 'Villa del rosario', 'department' => 'N. de santander'],
            817 => ['id' => '818', 'name' => 'Armenia', 'department' => 'Quindio'],
            818 => ['id' => '819', 'name' => 'Buenavista', 'department' => 'Quindio'],
            819 => ['id' => '820', 'name' => 'Calarca', 'department' => 'Quindio'],
            820 => ['id' => '821', 'name' => 'Circasia', 'department' => 'Quindio'],
            821 => ['id' => '822', 'name' => 'Cordoba', 'department' => 'Quindio'],
            822 => ['id' => '823', 'name' => 'Filandia', 'department' => 'Quindio'],
            823 => ['id' => '824', 'name' => 'Genova', 'department' => 'Quindio'],
            824 => ['id' => '825', 'name' => 'La tebaida', 'department' => 'Quindio'],
            825 => ['id' => '826', 'name' => 'Montenegro', 'department' => 'Quindio'],
            826 => ['id' => '827', 'name' => 'Pijao', 'department' => 'Quindio'],
            827 => ['id' => '828', 'name' => 'Quimbaya', 'department' => 'Quindio'],
            828 => ['id' => '829', 'name' => 'Salento', 'department' => 'Quindio'],
            829 => ['id' => '830', 'name' => 'Pereira', 'department' => 'Risaralda'],
            830 => ['id' => '831', 'name' => 'Apia', 'department' => 'Risaralda'],
            831 => ['id' => '832', 'name' => 'Balboa', 'department' => 'Risaralda'],
            832 => ['id' => '833', 'name' => 'Belen de umbria', 'department' => 'Risaralda'],
            833 => ['id' => '834', 'name' => 'Dosquebradas', 'department' => 'Risaralda'],
            834 => ['id' => '835', 'name' => 'Guatica', 'department' => 'Risaralda'],
            835 => ['id' => '836', 'name' => 'La celia', 'department' => 'Risaralda'],
            836 => ['id' => '837', 'name' => 'La virginia', 'department' => 'Risaralda'],
            837 => ['id' => '838', 'name' => 'Marsella', 'department' => 'Risaralda'],
            838 => ['id' => '839', 'name' => 'Mistrato', 'department' => 'Risaralda'],
            839 => ['id' => '840', 'name' => 'Pueblo rico', 'department' => 'Risaralda'],
            840 => ['id' => '841', 'name' => 'Quinchia', 'department' => 'Risaralda'],
            841 => ['id' => '842', 'name' => 'Santa rosa de cabal', 'department' => 'Risaralda'],
            842 => ['id' => '843', 'name' => 'Santuario', 'department' => 'Risaralda'],
            843 => ['id' => '844', 'name' => 'Bucaramanga', 'department' => 'Santander'],
            844 => ['id' => '845', 'name' => 'Aguada', 'department' => 'Santander'],
            845 => ['id' => '846', 'name' => 'Albania', 'department' => 'Santander'],
            846 => ['id' => '847', 'name' => 'Aratoca', 'department' => 'Santander'],
            847 => ['id' => '848', 'name' => 'Barbosa', 'department' => 'Santander'],
            848 => ['id' => '849', 'name' => 'Barichara', 'department' => 'Santander'],
            849 => ['id' => '850', 'name' => 'Barrancabermeja', 'department' => 'Santander'],
            850 => ['id' => '851', 'name' => 'Betulia', 'department' => 'Santander'],
            851 => ['id' => '852', 'name' => 'Bolivar', 'department' => 'Santander'],
            852 => ['id' => '853', 'name' => 'Cabrera', 'department' => 'Santander'],
            853 => ['id' => '854', 'name' => 'California', 'department' => 'Santander'],
            854 => ['id' => '855', 'name' => 'Capitanejo', 'department' => 'Santander'],
            855 => ['id' => '856', 'name' => 'Carcasi', 'department' => 'Santander'],
            856 => ['id' => '857', 'name' => 'Cepita', 'department' => 'Santander'],
            857 => ['id' => '858', 'name' => 'Cerrito', 'department' => 'Santander'],
            858 => ['id' => '859', 'name' => 'Charala', 'department' => 'Santander'],
            859 => ['id' => '860', 'name' => 'Charta', 'department' => 'Santander'],
            860 => ['id' => '861', 'name' => 'Chima', 'department' => 'Santander'],
            861 => ['id' => '862', 'name' => 'Chipata', 'department' => 'Santander'],
            862 => ['id' => '863', 'name' => 'Cimitarra', 'department' => 'Santander'],
            863 => ['id' => '864', 'name' => 'Concepcion', 'department' => 'Santander'],
            864 => ['id' => '865', 'name' => 'Confines', 'department' => 'Santander'],
            865 => ['id' => '866', 'name' => 'Contratacion', 'department' => 'Santander'],
            866 => ['id' => '867', 'name' => 'Coromoro', 'department' => 'Santander'],
            867 => ['id' => '868', 'name' => 'Curiti', 'department' => 'Santander'],
            868 => ['id' => '869', 'name' => 'El carmen de chucuri', 'department' => 'Santander'],
            869 => ['id' => '870', 'name' => 'El guacamayo', 'department' => 'Santander'],
            870 => ['id' => '871', 'name' => 'El peñon', 'department' => 'Santander'],
            871 => ['id' => '872', 'name' => 'El playon', 'department' => 'Santander'],
            872 => ['id' => '873', 'name' => 'Encino', 'department' => 'Santander'],
            873 => ['id' => '874', 'name' => 'Enciso', 'department' => 'Santander'],
            874 => ['id' => '875', 'name' => 'Florian', 'department' => 'Santander'],
            875 => ['id' => '876', 'name' => 'Floridablanca', 'department' => 'Santander'],
            876 => ['id' => '877', 'name' => 'Galan', 'department' => 'Santander'],
            877 => ['id' => '878', 'name' => 'Gambita', 'department' => 'Santander'],
            878 => ['id' => '879', 'name' => 'Giron', 'department' => 'Santander'],
            879 => ['id' => '880', 'name' => 'Guaca', 'department' => 'Santander'],
            880 => ['id' => '881', 'name' => 'Guadalupe', 'department' => 'Santander'],
            881 => ['id' => '882', 'name' => 'Guapota', 'department' => 'Santander'],
            882 => ['id' => '883', 'name' => 'Guavata', 'department' => 'Santander'],
            883 => ['id' => '884', 'name' => 'Gsepsa', 'department' => 'Santander'],
            884 => ['id' => '885', 'name' => 'Hato', 'department' => 'Santander'],
            885 => ['id' => '886', 'name' => 'Jesus maria', 'department' => 'Santander'],
            886 => ['id' => '887', 'name' => 'Jordan', 'department' => 'Santander'],
            887 => ['id' => '888', 'name' => 'La belleza', 'department' => 'Santander'],
            888 => ['id' => '889', 'name' => 'Landazuri', 'department' => 'Santander'],
            889 => ['id' => '890', 'name' => 'La paz', 'department' => 'Santander'],
            890 => ['id' => '891', 'name' => 'Lebrija', 'department' => 'Santander'],
            891 => ['id' => '892', 'name' => 'Los santos', 'department' => 'Santander'],
            892 => ['id' => '893', 'name' => 'Macaravita', 'department' => 'Santander'],
            893 => ['id' => '894', 'name' => 'Malaga', 'department' => 'Santander'],
            894 => ['id' => '895', 'name' => 'Matanza', 'department' => 'Santander'],
            895 => ['id' => '896', 'name' => 'Mogotes', 'department' => 'Santander'],
            896 => ['id' => '897', 'name' => 'Molagavita', 'department' => 'Santander'],
            897 => ['id' => '898', 'name' => 'Ocamonte', 'department' => 'Santander'],
            898 => ['id' => '899', 'name' => 'Oiba', 'department' => 'Santander'],
            899 => ['id' => '900', 'name' => 'Onzaga', 'department' => 'Santander'],
            900 => ['id' => '901', 'name' => 'Palmar', 'department' => 'Santander'],
            901 => ['id' => '902', 'name' => 'Palmas del socorro', 'department' => 'Santander'],
            902 => ['id' => '903', 'name' => 'Paramo', 'department' => 'Santander'],
            903 => ['id' => '904', 'name' => 'Piedecuesta', 'department' => 'Santander'],
            904 => ['id' => '905', 'name' => 'Pinchote', 'department' => 'Santander'],
            905 => ['id' => '906', 'name' => 'Puente nacional', 'department' => 'Santander'],
            906 => ['id' => '907', 'name' => 'Puerto parra', 'department' => 'Santander'],
            907 => ['id' => '908', 'name' => 'Puerto wilches', 'department' => 'Santander'],
            908 => ['id' => '909', 'name' => 'Rionegro', 'department' => 'Santander'],
            909 => ['id' => '910', 'name' => 'Sabana de torres', 'department' => 'Santander'],
            910 => ['id' => '911', 'name' => 'San andres', 'department' => 'Santander'],
            911 => ['id' => '912', 'name' => 'San benito', 'department' => 'Santander'],
            912 => ['id' => '913', 'name' => 'San gil', 'department' => 'Santander'],
            913 => ['id' => '914', 'name' => 'San joaquin', 'department' => 'Santander'],
            914 => ['id' => '915', 'name' => 'San jose de miranda', 'department' => 'Santander'],
            915 => ['id' => '916', 'name' => 'San miguel', 'department' => 'Santander'],
            916 => ['id' => '917', 'name' => 'San vicente de chucuri', 'department' => 'Santander'],
            917 => ['id' => '918', 'name' => 'Santa barbara', 'department' => 'Santander'],
            918 => ['id' => '919', 'name' => 'Santa helena del opon', 'department' => 'Santander'],
            919 => ['id' => '920', 'name' => 'Simacota', 'department' => 'Santander'],
            920 => ['id' => '921', 'name' => 'Socorro', 'department' => 'Santander'],
            921 => ['id' => '922', 'name' => 'Suaita', 'department' => 'Santander'],
            922 => ['id' => '923', 'name' => 'Sucre', 'department' => 'Santander'],
            923 => ['id' => '924', 'name' => 'Surata', 'department' => 'Santander'],
            924 => ['id' => '925', 'name' => 'Tona', 'department' => 'Santander'],
            925 => ['id' => '926', 'name' => 'Valle de san jose', 'department' => 'Santander'],
            926 => ['id' => '927', 'name' => 'Velez', 'department' => 'Santander'],
            927 => ['id' => '928', 'name' => 'Vetas', 'department' => 'Santander'],
            928 => ['id' => '929', 'name' => 'Villanueva', 'department' => 'Santander'],
            929 => ['id' => '930', 'name' => 'Zapatoca', 'department' => 'Santander'],
            930 => ['id' => '931', 'name' => 'Sincelejo', 'department' => 'Sucre'],
            931 => ['id' => '932', 'name' => 'Buenavista', 'department' => 'Sucre'],
            932 => ['id' => '933', 'name' => 'Caimito', 'department' => 'Sucre'],
            933 => ['id' => '934', 'name' => 'Coloso', 'department' => 'Sucre'],
            934 => ['id' => '935', 'name' => 'Corozal', 'department' => 'Sucre'],
            935 => ['id' => '936', 'name' => 'Coveñas', 'department' => 'Sucre'],
            936 => ['id' => '937', 'name' => 'Chalan', 'department' => 'Sucre'],
            937 => ['id' => '938', 'name' => 'El roble', 'department' => 'Sucre'],
            938 => ['id' => '939', 'name' => 'Galeras', 'department' => 'Sucre'],
            939 => ['id' => '940', 'name' => 'Guaranda', 'department' => 'Sucre'],
            940 => ['id' => '941', 'name' => 'La unión', 'department' => 'Sucre'],
            941 => ['id' => '942', 'name' => 'Los palmitos', 'department' => 'Sucre'],
            942 => ['id' => '943', 'name' => 'Majagual', 'department' => 'Sucre'],
            943 => ['id' => '944', 'name' => 'Morroa', 'department' => 'Sucre'],
            944 => ['id' => '945', 'name' => 'Ovejas', 'department' => 'Sucre'],
            945 => ['id' => '946', 'name' => 'Palmito', 'department' => 'Sucre'],
            946 => ['id' => '947', 'name' => 'Sampues', 'department' => 'Sucre'],
            947 => ['id' => '948', 'name' => 'San benito abad', 'department' => 'Sucre'],
            948 => ['id' => '949', 'name' => 'San juan de betulia', 'department' => 'Sucre'],
            949 => ['id' => '950', 'name' => 'San marcos', 'department' => 'Sucre'],
            950 => ['id' => '951', 'name' => 'San onofre', 'department' => 'Sucre'],
            951 => ['id' => '952', 'name' => 'San pedro', 'department' => 'Sucre'],
            952 => ['id' => '953', 'name' => 'San luis de since', 'department' => 'Sucre'],
            953 => ['id' => '954', 'name' => 'Sucre', 'department' => 'Sucre'],
            954 => ['id' => '955', 'name' => 'Santiago de tolu', 'department' => 'Sucre'],
            955 => ['id' => '956', 'name' => 'Tolu viejo', 'department' => 'Sucre'],
            956 => ['id' => '957', 'name' => 'Ibague', 'department' => 'Tolima'],
            957 => ['id' => '958', 'name' => 'Alpujarra', 'department' => 'Tolima'],
            958 => ['id' => '959', 'name' => 'Alvarado', 'department' => 'Tolima'],
            959 => ['id' => '960', 'name' => 'Ambalema', 'department' => 'Tolima'],
            960 => ['id' => '961', 'name' => 'Anzoategui', 'department' => 'Tolima'],
            961 => ['id' => '962', 'name' => 'Armero', 'department' => 'Tolima'],
            962 => ['id' => '963', 'name' => 'Ataco', 'department' => 'Tolima'],
            963 => ['id' => '964', 'name' => 'Cajamarca', 'department' => 'Tolima'],
            964 => ['id' => '965', 'name' => 'Carmen de apicala', 'department' => 'Tolima'],
            965 => ['id' => '966', 'name' => 'Casabianca', 'department' => 'Tolima'],
            966 => ['id' => '967', 'name' => 'Chaparral', 'department' => 'Tolima'],
            967 => ['id' => '968', 'name' => 'Coello', 'department' => 'Tolima'],
            968 => ['id' => '969', 'name' => 'Coyaima', 'department' => 'Tolima'],
            969 => ['id' => '970', 'name' => 'Cunday', 'department' => 'Tolima'],
            970 => ['id' => '971', 'name' => 'Dolores', 'department' => 'Tolima'],
            971 => ['id' => '972', 'name' => 'Espinal', 'department' => 'Tolima'],
            972 => ['id' => '973', 'name' => 'Falan', 'department' => 'Tolima'],
            973 => ['id' => '974', 'name' => 'Flandes', 'department' => 'Tolima'],
            974 => ['id' => '975', 'name' => 'Fresno', 'department' => 'Tolima'],
            975 => ['id' => '976', 'name' => 'Guamo', 'department' => 'Tolima'],
            976 => ['id' => '977', 'name' => 'Herveo', 'department' => 'Tolima'],
            977 => ['id' => '978', 'name' => 'Honda', 'department' => 'Tolima'],
            978 => ['id' => '979', 'name' => 'Icononzo', 'department' => 'Tolima'],
            979 => ['id' => '980', 'name' => 'Lerida', 'department' => 'Tolima'],
            980 => ['id' => '981', 'name' => 'Libano', 'department' => 'Tolima'],
            981 => ['id' => '982', 'name' => 'Mariquita', 'department' => 'Tolima'],
            982 => ['id' => '983', 'name' => 'Melgar', 'department' => 'Tolima'],
            983 => ['id' => '984', 'name' => 'Murillo', 'department' => 'Tolima'],
            984 => ['id' => '985', 'name' => 'Natagaima', 'department' => 'Tolima'],
            985 => ['id' => '986', 'name' => 'Ortega', 'department' => 'Tolima'],
            986 => ['id' => '987', 'name' => 'Palocabildo', 'department' => 'Tolima'],
            987 => ['id' => '988', 'name' => 'Piedras', 'department' => 'Tolima'],
            988 => ['id' => '989', 'name' => 'Planadas', 'department' => 'Tolima'],
            989 => ['id' => '990', 'name' => 'Prado', 'department' => 'Tolima'],
            990 => ['id' => '991', 'name' => 'Purificacion', 'department' => 'Tolima'],
            991 => ['id' => '992', 'name' => 'Rioblanco', 'department' => 'Tolima'],
            992 => ['id' => '993', 'name' => 'Roncesvalles', 'department' => 'Tolima'],
            993 => ['id' => '994', 'name' => 'Rovira', 'department' => 'Tolima'],
            994 => ['id' => '995', 'name' => 'Saldaña', 'department' => 'Tolima'],
            995 => ['id' => '996', 'name' => 'San antonio', 'department' => 'Tolima'],
            996 => ['id' => '997', 'name' => 'San luis', 'department' => 'Tolima'],
            997 => ['id' => '998', 'name' => 'Santa isabel', 'department' => 'Tolima'],
            998 => ['id' => '999', 'name' => 'Suarez', 'department' => 'Tolima'],
            999 => ['id' => '1000', 'name' => 'Valle de san juan', 'department' => 'Tolima'],
            1000 => ['id' => '1001', 'name' => 'Venadillo', 'department' => 'Tolima'],
            1001 => ['id' => '1002', 'name' => 'Villahermosa', 'department' => 'Tolima'],
            1002 => ['id' => '1003', 'name' => 'Villarrica', 'department' => 'Tolima'],
            1003 => ['id' => '1004', 'name' => 'Cali', 'department' => 'Valle del cauca'],
            1004 => ['id' => '1005', 'name' => 'Alcala', 'department' => 'Valle del cauca'],
            1005 => ['id' => '1006', 'name' => 'Andalucia', 'department' => 'Valle del cauca'],
            1006 => ['id' => '1007', 'name' => 'Ansermanuevo', 'department' => 'Valle del cauca'],
            1007 => ['id' => '1008', 'name' => 'Argelia', 'department' => 'Valle del cauca'],
            1008 => ['id' => '1009', 'name' => 'Bolivar', 'department' => 'Valle del cauca'],
            1009 => ['id' => '1010', 'name' => 'Buenaventura', 'department' => 'Valle del cauca'],
            1010 => ['id' => '1011', 'name' => 'Guadalajara de buga', 'department' => 'Valle del cauca'],
            1011 => ['id' => '1012', 'name' => 'Bugalagrande', 'department' => 'Valle del cauca'],
            1012 => ['id' => '1013', 'name' => 'Caicedonia', 'department' => 'Valle del cauca'],
            1013 => ['id' => '1014', 'name' => 'Calima', 'department' => 'Valle del cauca'],
            1014 => ['id' => '1015', 'name' => 'Candelaria', 'department' => 'Valle del cauca'],
            1015 => ['id' => '1016', 'name' => 'Cartago', 'department' => 'Valle del cauca'],
            1016 => ['id' => '1017', 'name' => 'Dagua', 'department' => 'Valle del cauca'],
            1017 => ['id' => '1018', 'name' => 'El aguila', 'department' => 'Valle del cauca'],
            1018 => ['id' => '1019', 'name' => 'El cairo', 'department' => 'Valle del cauca'],
            1019 => ['id' => '1020', 'name' => 'El cerrito', 'department' => 'Valle del cauca'],
            1020 => ['id' => '1021', 'name' => 'El dovio', 'department' => 'Valle del cauca'],
            1021 => ['id' => '1022', 'name' => 'Florida', 'department' => 'Valle del cauca'],
            1022 => ['id' => '1023', 'name' => 'Ginebra', 'department' => 'Valle del cauca'],
            1023 => ['id' => '1024', 'name' => 'Guacari', 'department' => 'Valle del cauca'],
            1024 => ['id' => '1025', 'name' => 'Jamundi', 'department' => 'Valle del cauca'],
            1025 => ['id' => '1026', 'name' => 'La cumbre', 'department' => 'Valle del cauca'],
            1026 => ['id' => '1027', 'name' => 'La union', 'department' => 'Valle del cauca'],
            1027 => ['id' => '1028', 'name' => 'La victoria', 'department' => 'Valle del cauca'],
            1028 => ['id' => '1029', 'name' => 'Obando', 'department' => 'Valle del cauca'],
            1029 => ['id' => '1030', 'name' => 'Palmira', 'department' => 'Valle del cauca'],
            1030 => ['id' => '1031', 'name' => 'Pradera', 'department' => 'Valle del cauca'],
            1031 => ['id' => '1032', 'name' => 'Restrepo', 'department' => 'Valle del cauca'],
            1032 => ['id' => '1033', 'name' => 'Riofrio', 'department' => 'Valle del cauca'],
            1033 => ['id' => '1034', 'name' => 'Roldanillo', 'department' => 'Valle del cauca'],
            1034 => ['id' => '1035', 'name' => 'San pedro', 'department' => 'Valle del cauca'],
            1035 => ['id' => '1036', 'name' => 'Sevilla', 'department' => 'Valle del cauca'],
            1036 => ['id' => '1037', 'name' => 'Toro', 'department' => 'Valle del cauca'],
            1037 => ['id' => '1038', 'name' => 'Trujillo', 'department' => 'Valle del cauca'],
            1038 => ['id' => '1039', 'name' => 'Tulua', 'department' => 'Valle del cauca'],
            1039 => ['id' => '1040', 'name' => 'Ulloa', 'department' => 'Valle del cauca'],
            1040 => ['id' => '1041', 'name' => 'Versalles', 'department' => 'Valle del cauca'],
            1041 => ['id' => '1042', 'name' => 'Vijes', 'department' => 'Valle del cauca'],
            1042 => ['id' => '1043', 'name' => 'Yotoco', 'department' => 'Valle del cauca'],
            1043 => ['id' => '1044', 'name' => 'Yumbo', 'department' => 'Valle del cauca'],
            1044 => ['id' => '1045', 'name' => 'Zarzal', 'department' => 'Valle del cauca'],
            1045 => ['id' => '1046', 'name' => 'Arauca', 'department' => 'Arauca'],
            1046 => ['id' => '1047', 'name' => 'Arauquita', 'department' => 'Arauca'],
            1047 => ['id' => '1048', 'name' => 'Cravo norte', 'department' => 'Arauca'],
            1048 => ['id' => '1049', 'name' => 'Fortul', 'department' => 'Arauca'],
            1049 => ['id' => '1050', 'name' => 'Puerto rondon', 'department' => 'Arauca'],
            1050 => ['id' => '1051', 'name' => 'Saravena', 'department' => 'Arauca'],
            1051 => ['id' => '1052', 'name' => 'Tame', 'department' => 'Arauca'],
            1052 => ['id' => '1053', 'name' => 'Yopal', 'department' => 'Casanare'],
            1053 => ['id' => '1054', 'name' => 'Aguazul', 'department' => 'Casanare'],
            1054 => ['id' => '1055', 'name' => 'Chameza', 'department' => 'Casanare'],
            1055 => ['id' => '1056', 'name' => 'Hato corozal', 'department' => 'Casanare'],
            1056 => ['id' => '1057', 'name' => 'La salina', 'department' => 'Casanare'],
            1057 => ['id' => '1058', 'name' => 'Mani', 'department' => 'Casanare'],
            1058 => ['id' => '1059', 'name' => 'Monterrey', 'department' => 'Casanare'],
            1059 => ['id' => '1060', 'name' => 'Nunchia', 'department' => 'Casanare'],
            1060 => ['id' => '1061', 'name' => 'Orocue', 'department' => 'Casanare'],
            1061 => ['id' => '1062', 'name' => 'Paz de ariporo', 'department' => 'Casanare'],
            1062 => ['id' => '1063', 'name' => 'Pore', 'department' => 'Casanare'],
            1063 => ['id' => '1064', 'name' => 'Recetor', 'department' => 'Casanare'],
            1064 => ['id' => '1065', 'name' => 'Sabanalarga', 'department' => 'Casanare'],
            1065 => ['id' => '1066', 'name' => 'Sacama', 'department' => 'Casanare'],
            1066 => ['id' => '1067', 'name' => 'San luis de palenque', 'department' => 'Casanare'],
            1067 => ['id' => '1068', 'name' => 'Tamara', 'department' => 'Casanare'],
            1068 => ['id' => '1069', 'name' => 'Tauramena', 'department' => 'Casanare'],
            1069 => ['id' => '1070', 'name' => 'Trinidad', 'department' => 'Casanare'],
            1070 => ['id' => '1071', 'name' => 'Villanueva', 'department' => 'Casanare'],
            1071 => ['id' => '1072', 'name' => 'Mocoa', 'department' => 'Putumayo'],
            1072 => ['id' => '1073', 'name' => 'Colon', 'department' => 'Putumayo'],
            1073 => ['id' => '1074', 'name' => 'Orito', 'department' => 'Putumayo'],
            1074 => ['id' => '1075', 'name' => 'Puerto asis', 'department' => 'Putumayo'],
            1075 => ['id' => '1076', 'name' => 'Puerto caicedo', 'department' => 'Putumayo'],
            1076 => ['id' => '1077', 'name' => 'Puerto guzman', 'department' => 'Putumayo'],
            1077 => ['id' => '1078', 'name' => 'Leguizamo', 'department' => 'Putumayo'],
            1078 => ['id' => '1079', 'name' => 'Sibundoy', 'department' => 'Putumayo'],
            1079 => ['id' => '1080', 'name' => 'San francisco', 'department' => 'Putumayo'],
            1080 => ['id' => '1081', 'name' => 'San miguel', 'department' => 'Putumayo'],
            1081 => ['id' => '1082', 'name' => 'Santiago', 'department' => 'Putumayo'],
            1082 => ['id' => '1083', 'name' => 'Valle del guamuez', 'department' => 'Putumayo'],
            1083 => ['id' => '1084', 'name' => 'Villagarzon', 'department' => 'Putumayo'],
            1084 => ['id' => '1085', 'name' => 'San andres', 'department' => 'San andres'],
            1085 => ['id' => '1086', 'name' => 'Providencia', 'department' => 'San andres'],
            1086 => ['id' => '1087', 'name' => 'Leticia', 'department' => 'Amazonas'],
            1087 => ['id' => '1088', 'name' => 'El encanto', 'department' => 'Amazonas'],
            1088 => ['id' => '1089', 'name' => 'La chorrera', 'department' => 'Amazonas'],
            1089 => ['id' => '1090', 'name' => 'La pedrera', 'department' => 'Amazonas'],
            1090 => ['id' => '1091', 'name' => 'La victoria', 'department' => 'Amazonas'],
            1091 => ['id' => '1092', 'name' => 'Miriti - parana', 'department' => 'Amazonas'],
            1092 => ['id' => '1093', 'name' => 'Puerto alegria', 'department' => 'Amazonas'],
            1093 => ['id' => '1094', 'name' => 'Puerto arica', 'department' => 'Amazonas'],
            1094 => ['id' => '1095', 'name' => 'Puerto nariño', 'department' => 'Amazonas'],
            1095 => ['id' => '1096', 'name' => 'Puerto santander', 'department' => 'Amazonas'],
            1096 => ['id' => '1097', 'name' => 'Tarapaca', 'department' => 'Amazonas'],
            1097 => ['id' => '1098', 'name' => 'Inirida', 'department' => 'Guainia'],
            1098 => ['id' => '1099', 'name' => 'Barranco minas', 'department' => 'Guainia'],
            1099 => ['id' => '1100', 'name' => 'Mapiripana', 'department' => 'Guainia'],
            1100 => ['id' => '1101', 'name' => 'San felipe', 'department' => 'Guainia'],
            1101 => ['id' => '1102', 'name' => 'Puerto colombia', 'department' => 'Guainia'],
            1102 => ['id' => '1103', 'name' => 'La guadalupe', 'department' => 'Guainia'],
            1103 => ['id' => '1104', 'name' => 'Cacahual', 'department' => 'Guainia'],
            1104 => ['id' => '1105', 'name' => 'Pana pana', 'department' => 'Guainia'],
            1105 => ['id' => '1106', 'name' => 'Morichal', 'department' => 'Guainia'],
            1106 => ['id' => '1107', 'name' => 'San jose del guaviare', 'department' => 'Guaviare'],
            1107 => ['id' => '1108', 'name' => 'Calamar', 'department' => 'Guaviare'],
            1108 => ['id' => '1109', 'name' => 'El retorno', 'department' => 'Guaviare'],
            1109 => ['id' => '1110', 'name' => 'Miraflores', 'department' => 'Guaviare'],
            1110 => ['id' => '1111', 'name' => 'Mitu', 'department' => 'Vaupes'],
            1111 => ['id' => '1112', 'name' => 'Caruru', 'department' => 'Vaupes'],
            1112 => ['id' => '1113', 'name' => 'Pacoa', 'department' => 'Vaupes'],
            1113 => ['id' => '1114', 'name' => 'Taraira', 'department' => 'Vaupes'],
            1114 => ['id' => '1115', 'name' => 'Papunaua', 'department' => 'Vaupes'],
            1115 => ['id' => '1116', 'name' => 'Yavarate', 'department' => 'Vaupes'],
            1116 => ['id' => '1117', 'name' => 'Puerto carreño', 'department' => 'Vichada'],
            1117 => ['id' => '1118', 'name' => 'La primavera', 'department' => 'Vichada'],
            1118 => ['id' => '1119', 'name' => 'Santa rosalia', 'department' => 'Vichada'],
            1119 => ['id' => '1120', 'name' => 'Cumaribo', 'department' => 'Vichada'],
        ];
    }
}
